
tweaks={
  medic={
    AutopsyReport={
      colors=2},
    ChiefOfStaff={
      create="Left glasses orange seepthrough"},
    DoesItHurtWhenIDoThis={
      colors=2,
      separate="Rightmost tooth"},
    DoubleBlindTrial={
      separate="Right Medic inner ear",
      forced_cutout=true},
    FamilyPractice={
      merge="Bottom Medic's hand (gripping Spy)",
      carve="Bottom Medic's coat tail separator"},
    FYIIAmAMedic={
      special="Photograph settings"},
    Intern={
      merge="Background under base of plunger of topmost syringe"},
    PeerReview={
      colors=2},
    PlaceboEffect={
      smooth="Left side of Medic"},
    TraumaQueen={
      smooth="Smallest ripple on left"},
  },
  pyro={
    barbequeq={
      colors=2},
    combined_fire={
      colors=2},
    dance_dance_immolation={
      colors=5,
      zap="Around tank of white Pyro's flamethrower",
      create="Darker orange section under head of brightest Pyro",
      carve="Darker orange hose by brighter orange"},
    i_fry={
      unite="Right side of nose (touch middle part with diagonal pixel)"},
    pyro_achieve_progress2={
      zap="bottom of middle balloon's string"},
    pyro_achieve_progress2={
      special="Essentially the same as tf_heavy_achieve_progress3"},
    pyromancer={
      colors=6},
    spontaneous_combustion={
      colors=2},
    trailblazer={
      smooth="Bottom of top ring"},
  },
  heavy={
    tf_heavy_achieve_progress2={
      fill="Bottom of middle balloon string"},
    tf_heavy_assist_grind={
      colors=2},
    tf_heavy_block_invuln_heavy={
      colors=2},
    tf_heavy_clear_stickybombs={
      zap="Middle and bottom spikes on right side"},
    tf_heavy_clear_stickybombs={
      zap="Middle and bottom spikes on right side"},
    tf_heavy_defend_medic={
      colors=2},
    tf_heavy_eat_sandwiches={
      colors=2},
    tf_heavy_fire_lots={
      colors=2},
    tf_heavy_kill_midair_minigun={
      smooth="Bottom of Medic's glove"},
    tf_heavy_kill_midair_minigun={
      colors=2},
    tf_heavy_kill_shotgun={
      colors=2},
--  tf_heavy_kill_underwater={
--    create="Little bit to the left of the bottom fin"},
    tf_heavy_payload_cap_grind={
      colors=2},
    tf_heavy_stand_near_dispenser={
      colors=2},
    tf_heavy_survive_crocket={
      colors=2},
    tf_heavy_uncover_spies={
      colors=2},
  },
  scout={
    artful_dodger={
      colors=2},
    block_the_plate={
      zap="Top of fold in hand that's a lighter gray in the original",
      smooth="Bottom-left of middle ring on plate"},
    brushback={
      merge="Bottom of bottom rivet on bomb casing"},
    caught_napping={
      colors=2},
    doctoring_the_ball={
      create="Right eye",
      merge="Top of glow"},
    first_blood={
      merge="Lightning above head"},
    first_blood_part_2={
      expand="Leftmost spot",
      create="Tick nearest tip",
      merge="Line on right side of bat"},
    gun_down={
      colors=2},
    if_you_build_it={
      colors=2},
    im_bat_man={
      colors=2},
    pop_fly={
      zap="Inside of left burst's top ray"},
    race_for_the_pennant={
      colors=4},
    round_tripper={
      colors=2},
    set_the_table={
      colors=5,
      expand="Hat brims on darker colors"},
    side_retired={
      zap="Topmost plate",
      merge="Rings",
      separate="Rings"},
    tf_scout_achieve_progress2={
      fill="Bottom of middle balloon string"},
    triple_play={
      colors=4,
      merge="Second ring on back plate"},
    triple_steal={
      colors=2},
  },
  sniper={
    tf_sniper_australian_rules={
      colors="unlimited"},
    tf_sniper_be_polite={
      carve="Folds inside hat, jowl, top of thing on back",
      expand="White on lower side of strap",
      separate="head and neck"},
    tf_sniper_beaux_and_arrows={
      colors=5,
      manual_palette="Get top and second-row crosses"},
    tf_sniper_consolation_prize={
      separate="right screw",
      create="top part of below-rightmost tab on ribbon"},
    tf_sniper_de-sentry-lized={
      separate="Hinge and body"},
    tf_sniper_enemy_at_the_gate={
      colors=4},
    tf_sniper_friendship_is_golden={
      colors=4},
    tf_sniper_jarate_chop={
      colors=5},
    tf_sniper_jarring_transition={
      colors=5},
    tf_sniper_jumper_stumper={
      merge="back of skirt thing",
      separate="right grenade"},
    tf_sniper_kill_everyone_you_meet={
      create="lenscap, scope, sleeve details"},
    tf_sniper_kook_the_spook-{
      separate="Spots on collar",
      zap="Top edge of kukri",
      create="Right fold of collar, spot on left side of collar",
      smooth="Top-right side of eye hole"},
    tf_sniper_my_brilliant_career={
      separate="Bottom-left spot on #",
      expand="Bottom-left spot on #, spots on left side of 1",
      create="Spots in other 2 quadrants of #"},
    tf_sniper_not_a_crazed_gunman_dad={
      smooth="Underside of Pyro tank"}, --artifacts?
    tf_sniper_number_one_assistant={
      colors=6},
    tf_sniper_parting_shot={
      colors=5,
      create="Third figure's arm near tip of orange figure's high hand"},
    tf_sniper_pincushion={
      colors=8,
      manual_palette="Brown, stubble, highlight line on chin, lower 3 bullets, bottom of nose",
      zap="behind ear",
      fill="grey parts of eyes to brown",
      create="light orange part of back collar, parts of wrap on nearby arrow and by ear"},
    tf_sniper_rain_on_their_parade={
      zap="right line in Medic",
      create="line on Demoman's cheek, lines on Medic's face",
      separate="eyebrow and eyepatch,Medic top lip and front teeth"},
    tf_sniper_robbin_hood={
      create="arrow wraps",
      separate="bottom of papers on right"},
    tf_sniper_shafted={
      colors=4},
    tf_sniper_socket_to_him={
      colors=4},
    tf_sniper_uberectomy={
      colors=4},
    tf_sniper_william_tell_overkill={
      colors=4},
  },
  spy={
  },
  soldier={
  },
  demoman={
  },
}
--CHECK SHAPE MODE IN EXPORT OPTIONS BEFORE SAVING!
