
tweaks={
  medic={
    AutopsyReport={
      colors=2},
    ChiefOfStaff={
      create="Left glasses orange seepthrough"},
    DoesItHurtWhenIDoThis={
      colors=2,
      separate="Rightmost tooth"},
    DoubleBlindTrial={
      separate="Right Medic inner ear",
      forced_cutout=true},
    FamilyPractice={
      merge="Bottom Medic's hand (gripping Spy)",
      carve="Bottom Medic's coat tail separator"},
    FYIIAmAMedic={
      special="Photograph settings"},
    Intern={
      merge="Background under base of plunger of topmost syringe"},
    PeerReview={
      colors=2},
    PlaceboEffect={
      smooth="Left side of Medic"},
    TraumaQueen={
      smooth="Smallest ripple on left"},
  },
  pyro={
    barbequeq={
      colors=2},
    combined_fire={
      colors=2},
    dance_dance_immolation={
      colors=5,
      zap="Around tank of white Pyro's flamethrower",
      create="Darker orange section under head of brightest Pyro",
      carve="Darker orange hose by brighter orange"},
    i_fry={
      unite="Right side of nose (touch middle part with diagonal pixel)"},
    pyro_achieve_progress2={
      zap="bottom of middle balloon's string"},
    pyro_achieve_progress2={
      special="Essentially the same as tf_heavy_achieve_progress3"},
    pyromancer={
      colors=6},
    spontaneous_combustion={
      colors=2},
    trailblazer={
      smooth="Bottom of top ring"},
  },
  heavy={
    tf_heavy_achieve_progress2={
      fill="Bottom of middle balloon string"},
    tf_heavy_assist_grind={
      colors=2},
    tf_heavy_block_invuln_heavy={
      colors=2},
    tf_heavy_clear_stickybombs={
      zap="Middle and bottom spikes on right side"},
    tf_heavy_clear_stickybombs={
      zap="Middle and bottom spikes on right side"},
    tf_heavy_defend_medic={
      colors=2},
    tf_heavy_eat_sandwiches={
      colors=2},
    tf_heavy_fire_lots={
      colors=2},
    tf_heavy_kill_midair_minigun={
      smooth="Bottom of Medic's glove"},
    tf_heavy_kill_midair_minigun={
      colors=2},
    tf_heavy_kill_shotgun={
      colors=2},
--  tf_heavy_kill_underwater={
--    create="Little bit to the left of the bottom fin"},
    tf_heavy_payload_cap_grind={
      colors=2},
    tf_heavy_stand_near_dispenser={
      colors=2},
    tf_heavy_survive_crocket={
      colors=2},
    tf_heavy_uncover_spies={
      colors=2},
  },
  scout={
    artful_dodger={
      colors=2},
    block_the_plate={
      zap="Top of fold in hand that's a lighter gray in the original",
      smooth="Bottom-left of middle ring on plate"},
    brushback={
      merge="Bottom of bottom rivet on bomb casing"},
    caught_napping={
      colors=2},
    doctoring_the_ball={
      create="Right eye",
      merge="Top of glow"},
    first_blood={
      merge="Lightning above head"},
    gun_down={
      colors=2},
    if_you_build_it={
      colors=2},
    im_bat_man={
      colors=2},
    race_for_the_pennant={
      colors=4},
      round_tripper={
      colors=2},
    set_the_table={
      colors=5},
    triple_play={
      colors=4},
    triple_steal={
      colors=2},


}
--CHECK SHAPE MODE IN EXPORT OPTIONS BEFORE SAVING!
