--encoding: utf-8
--(the Ü in Übercharge, fancy quote characters)

tf={
  medic ={
    top_scoreboard ={ name= "First Do No Harm",
      desc= "Play a full round without killing any enemies, and score the highest on a team of 6 or more players."},
    heal_under_fire ={ name= "Quadruple Bypass",
      desc= "Heal a teammate who's taking fire from 4 enemies at once."},
    simul_charge ={ name= "Group Health",
      desc= "Work with 2 other Medics to deploy 3 simultaneous ÜberCharges."},
    setup_charge ={ name= "Surgical Prep",
      desc= "Have an ÜberCharge ready before the Setup phase ends."},
    rapid_charge ={ name= "Trauma Queen",
      desc= "Deploy 3 ÜberCharges in less than 5 minutes, and assist in 5 kills during that time."},
    counter_charge ={ name= "Double Blind Trial",
      desc= "Deploy an ÜberCharge within 8 seconds of a nearby enemy Medic deploying his."},
    switch_to_medic ={ name= "Play Doctor",
      desc= "In a team with no Medics, be the first person to switch to Medic after a teammate calls for 'Medic!', and then heal 500 health."},
    save_teammate ={ name= "Triage",
      desc= "Deploy an ÜberCharge on a teammate less than a second before they're hit by a critical explosive."},
    charge_blocker ={ name= "Preventive Medicine",
      desc= "Block the enemy from capturing a control point with an ÜberCharged teammate."},
    assist_medic ={ name= "Consultation",
      desc= "Assist a fellow Medic in killing 5 enemies in a single life."},
    syringe_scouts ={ name= "Does It Hurt When I Do This?",
      desc= "Kill 50 Scouts with your syringe gun."},
    bonesaw_medics ={ name= "Peer Review",
      desc= "Kill 50 Medics with your bone saw."},
    assist_heavy_long ={ name= "Big Pharma",
      desc= "Assist a Heavy in killing 10 enemies, where neither of you die."},
    assist_scout ={ name= "You'll Feel a Little Prick",
      desc= "Assist in killing 3 enemies with a single ÜberCharge on a Scout."},
    assist_pyro ={ name= "Autoclave",
      desc= "Assist in burning 5 enemies with a single ÜberCharge on a Pyro."},
    assist_heavy ={ name= "Blunt Trauma",
      desc= "Assist in punching 2 enemies with a single ÜberCharge on a Heavy."},
    assist_demoman ={ name= "Medical Breakthrough",
      desc= "Assist in destroying 5 enemy Engineer buildings with a single ÜberCharge on a Demoman."},
    assist_soldier ={ name= "Blast Assist",
      desc= "Assist in exploding 5 enemies with a single ÜberCharge on a Soldier."},
    heal_engineer ={ name= "Midwife Crisis",
      desc= "Heal an Engineer as he repairs his sentry gun while it's under enemy fire."},
    assist_capturer ={ name= "Ubi concordia, ibi victoria",
      desc= "Assist in killing 3 enemies on an enemy control point, in a single life."},
    heal_callers ={ name= "Grand Rounds",
      desc= "Heal 200 teammates after they've called for 'Medic!'."},
    extinguish_teammates ={ name= "Infernal Medicine",
      desc= "Extinguish 100 burning teammates."},
    assist_vs_nemeses ={ name= "Doctor Assisted Homicide",
      desc= "Assist in killing 20 nemeses."},
    kill_while_charged ={ name= "Placebo Effect",
      desc= "Kill 5 enemies in a single life, while having your ÜberCharge ready, but undeployed."},
    bonesaw_nomisses ={ name= "Sawbones",
      desc= "Hit enemies with your bonesaw 5 times in a row without dying or missing."},
    heal_large ={ name= "Intern",
      desc= "Accumulate 7000 heal points in a single life."},
    heal_huge ={ name= "Specialist",
      desc= "Accumulate 10000 heal points health in a single life."},
    heal_grind ={ name= "Chief of Staff",
      desc= "Accumulate 1 million total heal points."},
    kill_healed_spy ={ name= "Hypocritical Oath",
      desc= "Kill an enemy Spy that you have been healing."},
    save_falling_teammate ={ name= "Medical Intervention",
      desc= "Save a falling teammate from dying on impact."},
    charge_juggle ={ name= "Second Opinion",
      desc= "ÜberCharge 2 teammates at once."},
    freezecam_ragdoll ={ name= "Autopsy Report",
      desc= "Provide an enemy with a freezecam shot of you taunting above their ragdoll."},
    bonesaw_spy_callers ={ name= "FYI I am A Medic",
      desc= "Use your bonesaw to kill 5 Spies who have been calling for 'Medic!'."},
    charge_friends ={ name= "Family Practice",
      desc= "ÜberCharge ten of your Steam Community Friends."},
    invite_join_charge ={ name= "House Call",
      desc= "Join a game that one of your friends is in and then deploy an ÜberCharge on him."},
    heal_achiever ={ name= "Bedside Manner",
      desc= "Be healing a teammate as he achieves an achievement of his own."},
    achieve_progress1 ={ name= "Medic Milestone 1",
      desc= "Achieve 10 of the achievements in the Medic pack."},
    achieve_progress2 ={ name= "Medic Milestone 2",
      desc= "Achieve 16 of the achievements in the Medic pack."},
    achieve_progress3 ={ name= "Medic Milestone 3",
      desc= "Achieve 22 of the achievements in the Medic pack."},
  },
  pyro ={
    kill_multiweapons ={ name= "Combined Fire",
      desc= "Use your shotgun to finish off 20 players you've ignited."},
    simulburn_scouts ={ name= "Weenie Roast",
      desc= "Have 2 enemy Scouts on fire at the same time."},
    force_waterjump ={ name= "Baptism by Fire",
      desc= "Force 10 burning enemies to jump into water."},
    kill_postdeath ={ name= "Fire and Forget",
      desc= "Kill 15 players while you're dead."},
    kill_spies ={ name= "Firewall",
      desc= "Ignite 5 Spies who have a sapper on a friendly building."},
    kill_carriers ={ name= "Cooking the Books",
      desc= "Ignite 5 enemies carrying your intelligence."},
    reveal_spies ={ name= "Spontaneous Combustion",
      desc= "Ignite 10 cloaked Spies."},
    camp_teleporters ={ name= "Trailblazer",
      desc= "Ignite 10 enemies that have recently used a teleporter."},
    camp_position ={ name= "Camp Fire",
      desc= "Kill 3 enemies in a row, all within the same area."},
    kill_axe_small ={ name= "Lumberjack",
      desc= "Kill 3 people with your axe in one life."},
    kill_axe_large ={ name= "Clearcutter",
      desc= "Kill 6 people with your axe in one life."},
    kill_from_behind ={ name= "Hot on Your Heels",
      desc= "Kill 50 enemies with your flamethrower, from behind."},
    burn_spies_as_you ={ name= "I Fry",
      desc= "Ignite 10 disguised Spies."},
    burn_snipers_zoomed ={ name= "Firewatch",
      desc= "Ignite 10 Snipers while they are zoomed in."},
    burn_medics_charged ={ name= "Burn Ward",
      desc= "Ignite 3 Medics that are ready to deploy an ÜberCharge."},
    reflect_projectiles ={ name= "Hot Potato",
      desc= "Reflect 100 projectiles with your compressed air blast."},
    kill_heavies ={ name= "Makin' Bacon",
      desc= "Kill 50 Heavies with your flamethrower."},
    kill_underwater ={ name= "Plan B",
      desc= "Kill 10 enemies while you're both underwater."},
    kill_ubercharge ={ name= "Pyrotechnics",
      desc= "Kill 3 enemies in a single ÜberCharge."},
    destroy_buildings ={ name= "Arsonist",
      desc= "Destroy 50 Engineer buildings."},
    defend_points ={ name= "Controlled Burn",
      desc= "Ignite 50 enemies capturing one of your control points."},
    kill_grind ={ name= "Firefighter",
      desc= "Kill 500 enemies."},
    damage_grind ={ name= "Pyromancer",
      desc= "Do 1 million points of total fire damage."},
    burn_medicpair ={ name= "Next of Kindling",
      desc= "Ignite an enemy, and the Medic healing him."},
    kill_taunt ={ name= "OMGWTFBBQ",
      desc= "Kill an enemy with a taunt."},
    kill_teamwork ={ name= "Second Degree Burn",
      desc= "Kill a burning enemy who was ignited by another Pyro."},
    burn_spy_taunt ={ name= "Got A Light?",
      desc= "Ignite an enemy Spy while he's flicking a cigarette."},
    dominate_leavesvr ={ name= "BarbeQueQ",
      desc= "Cause a dominated player to leave the server."},
    reflect_crocket_kill ={ name= "Hotshot",
      desc= "Kill a Soldier with a reflected critical rocket."},
    kill_taunters ={ name= "Dance Dance Immolation",
      desc= "Kill 3 enemies while they're taunting."},
    double_ko ={ name= "Dead Heat",
      desc= "Kill an enemy in the same second that he kills you."},
    burn_rj_soldier ={ name= "Pilot Light",
      desc= "Ignite a rocket-jumping Soldier while he's in midair."},
    freezecam_taunts ={ name= "Freezer Burn",
      desc= "Provide enemies with freezecam shots of each of your taunts."},
    kill_grind_large ={ name= "Fire Chief",
      desc= "Kill 1000 enemies."},
    ignite_flaregun ={ name= "Attention Getter",
      desc= "Ignite 100 enemies with the flare gun."},
    achieve_progress1 ={ name= "Pyro Milestone 1",
      desc= "Achieve 10 of the achievements in the Pyro pack."},
    achieve_progress2 ={ name= "Pyro Milestone 2",
      desc= "Achieve 16 of the achievements in the Pyro pack."},
    achieve_progress3 ={ name= "Pyro Milestone 3",
      desc= "Achieve 22 of the achievements in the Pyro pack."},
  },
  heavy ={
    damage_taken ={ name= "Iron Kurtain",
      desc= "Take 1000 points of damage in a single life."},
    defend_medic ={ name= "Party Loyalty",
      desc= "Kill 50 enemies within 3 seconds of them attacking your Medic."},
    assist_medic_large ={ name= "Division of Labor",
      desc= "Kill 10 enemies with a Medic assisting you, where neither of you die."},
    earn_medic_domination ={ name= "Red Oktoberfest",
      desc= "Earn a domination for a Medic who's healing you."},
    kill_taunt ={ name= "Show Trial",
      desc= "Kill an enemy with a taunt."},
    kill_flag_carriers ={ name= "Crime and Punishment",
      desc= "Kill 10 enemies carrying your intelligence."},
    kill_medic_pair ={ name= "Class Struggle",
      desc= "Work with a friendly Medic to kill an enemy Heavy & Medic pair."},
    block_invuln_heavy ={ name= "Soviet Block",
      desc= "While invulnerable and on defense, block an invulnerable enemy Heavy's movement."},
    block_cart ={ name= "Stalin the Kart",
      desc= "Block the enemy from moving the payload cart 25 times."},
    receive_uber_grind ={ name= "Supreme Soviet",
      desc= "Get ÜberCharged 50 times."},
    stand_near_dispenser ={ name= "Factory Worker",
      desc= "Kill 20 enemies while being recharged by a dispenser."},
    assist_heavy_grind ={ name= "Soviet Union",
      desc= "Get 25 enemy kills where you either assist or are assisted by another Heavy."},
    clear_stickybombs ={ name= "0wn the Means of Production",
      desc= "Remove 20 stickybombs by killing the Demomen who produced them."},
    kill_underwater ={ name= "Krazy Ivan",
      desc= "Kill 100 enemies while both you and your victim are underwater."},
    take_multi_damage ={ name= "Rasputin",
      desc= "In a single life, get shot, burned, bludgeoned, and receive explosive damage."},
    kill_dominated ={ name= "Icing on the Cake",
      desc= "Get 20 kills on players that you're dominating."},
    survive_crocket ={ name= "Crock Block",
      desc= "Survive a direct hit from a critical rocket."},
    assist_grind ={ name= "Kollectivization",
      desc= "Get 1000 assists."},
    uncover_spies ={ name= "Spyalectical Materialism",
      desc= "Kill or assist in killing 10 cloaked Spies."},
    kill_while_spunup ={ name= "Permanent Revolution",
      desc= "Kill 5 enemies without spinning down your gun."},
    fire_lots ={ name= "Heavy Industry",
      desc= "Fire $200,000 worth of minigun rounds in a single life."},
    kill_crit_punch ={ name= "Communist Mani-Fisto",
      desc= "Kill an enemy with a critical punch."},
    heal_medikits ={ name= "Redistribution of Health",
      desc= "Heal 1000 damage with med-kits in a single life."},
    kill_shotgun ={ name= "Rationing",
      desc= "Kill an enemy with your shotgun while you're out of minigun ammo."},
    first_to_cap ={ name= "Vanguard Party",
      desc= "Be the first on your team to start capturing a control point in a round."},
    payload_cap_grind ={ name= "Pushkin the Kart",
      desc= "Get 50 caps on payload maps."},
    kill_midair_minigun ={ name= "Marxman",
      desc= "Kill 10 enemies in mid-air with the minigun."},
    defend_control_point ={ name= "Gorky Parked",
      desc= "Kill 25 enemies while you're standing on a control point you own."},
    kill_capping_enemies ={ name= "Purge",
      desc= "Kill 15 enemies capturing a control point you own."},
    revenge_assist ={ name= "Lenin A Hand",
      desc= "Help 5 teammates get revenge on their nemeses."},
    teleport_fast_kill ={ name= "Five Second Plan",
      desc= "Kill an enemy in the first 5 seconds after you exit a teleporter."},
    freezecam_taunt ={ name= "Photostroika",
      desc= "Provide an enemy with a freezecam shot of you taunting while invulnerable."},
    eat_sandwiches ={ name= "Konspicuous Konsumption",
      desc= "Eat 100 sandviches."},
    kill_scouts ={ name= "Don't Touch Sandvich",
      desc= "Kill 50 Scouts using Natascha."},
    kill_heavies_gloves ={ name= "Borscht Belt",
      desc= "Kill 10 Heavies with The K.G.B."},
    achieve_progress1 ={ name= "Heavy Milestone 1",
      desc= "Achieve 10 of the achievements in the Heavy pack."},
    achieve_progress2 ={ name= "Heavy Milestone 2",
      desc= "Achieve 16 of the achievements in the Heavy pack."},
    achieve_progress3 ={ name= "Heavy Milestone 3",
      desc= "Achieve 22 of the achievements in the Heavy pack."},
  },
  scout ={
    first_blood ={ name= "First Blood",
      desc= "Get the first kill in an Arena match."},
    first_blood_kill ={ name= "First Blood, Part 2",
      desc= "Kill 5 enemies with the First Blood crit buff."},
    well_early_kill ={ name= "Quick Hook",
      desc= "Kill a player in Well before the round starts."},
    lifetime_kills ={ name= "A Year to Remember",
      desc= "Get 2004 lifetime kills."},
    iron_man_kills ={ name= "The Cycle",
      desc= "In a single life, kill an enemy while you are on the ground, in the air, and in the water."},
    destroy_teleporters ={ name= "Closer",
      desc= "Destroy 3 teleporter entrances."},
    destroy_buildings_being_built ={ name= "If You Build It",
      desc= "Destroy 3 enemy buildings while they are still under construction."},
    destroy_sentry_with_pistol ={ name= "Gun Down",
      desc= "Destroy an active sentry gun using your pistol."},
    double_jumps ={ name= "Batter Up",
      desc= "Perform 1000 double jumps."},
    assist_medic ={ name= "Doctoring the Ball",
      desc= "Kill 3 enemies while under the effects of a Medic's ÜberCharge."},
    steal_sandwich ={ name= "Dodgers 1, Giants 0",
      desc= "Kill an enemy Heavy and take his Sandvich."},
    achieve_progress1 ={ name= "Scout Milestone 1",
      desc= "Achieve 10 of the achievements in the Scout pack."},
    achieve_progress2 ={ name= "Scout Milestone 2",
      desc= "Achieve 16 of the achievements in the Scout pack."},
    achieve_progress3 ={ name= "Scout Milestone 3",
      desc= "Achieve 22 of the achievements in the Scout pack."},
    kill_charged_medics ={ name= "Batting the Doctor",
      desc= "Kill a Medic that is ready to deploy an ÜberCharge."},
    survive_damage ={ name= "I'm Bat Man",
      desc= "Survive 500 damage in one life."},
    doublejump_kill ={ name= "Pop Fly",
      desc= "Kill 20 players while double-jumping."},
    flag_cap_grind ={ name= "Round-Tripper",
      desc= "Capture the enemy intelligence 25 times."},
    three_flagcaps ={ name= "Triple Steal",
      desc= "Capture the enemy intelligence 3 times in a single CTF round."},
    dodge_damage ={ name= "Artful Dodger",
      desc= "Dodge 1000 damage in a single life using your Bonk! Atomic Punch."},
    knock_into_train ={ name= "Fall Classic",
      desc= "Cause an environmental death or suicide using the Force-A-Nature's knockback."},
    kill_stunned ={ name= "Strike Zone",
      desc= "Kill 50 enemies while they are stunned."},
    stun_into_train ={ name= "Foul Territory",
      desc= "Cause an environmental death by stunning an enemy."},
    stun_uber_enemies ={ name= "The Big Hurt",
      desc= "Stun 2 Medics that are ready to deploy an ÜberCharge."},
    stun_capping_enemies ={ name= "Brushback",
      desc= "Stun 50 enemies while they are capturing a point or pushing the cart."},
    max_stuns ={ name= "Moon Shot",
      desc= "Stun an enemy for the maximum possible duration by hitting them with a long-range ball."},
    stun_scout_with_their_ball ={ name= "Beanball",
      desc= "Stun a Scout with their own ball."},
    kill_in_dodge_cooldown ={ name= "Retire the Runner",
      desc= "Kill a Scout while they are under the effect of Crit-a-Cola."},
    kill_from_behind ={ name= "Caught Napping",
      desc= "Kill 50 enemies from behind with the Force-A-Nature."},
    capture_last_point ={ name= "Side Retired",
      desc= "Capture the last point in a CP map."},
    capture_three_points ={ name= "Triple Play",
      desc= "Capture three capture points in a row in one life."},
    fast_cap ={ name= "Stealing Home",
      desc= "Start capping a capture point within a second of it becoming available."},
    start_and_finish_cap ={ name= "Set the Table",
      desc= "Initiate 10 point captures that ultimately succeed."},
    block_caps ={ name= "Block the Plate",
      desc= "Block 50 point captures."},
    carrier_kill_carrier ={ name= "Belittled Beleaguer",
      desc= "Kill an opposing player that has your intelligence while holding theirs."},
    cap_flag_without_attacking ={ name= "No-Hitter",
      desc= "Steal and then capture the enemy intelligence without firing a shot."},
    long_distance_runner ={ name= "Race for the Pennant",
      desc= "Run 25 kilometers."},
    taunt_kill ={ name= "Out of the Park",
      desc= "Bat an enemy 25 meters."},
  },
  sniper ={
    jarate_dominated ={ name= "Rode Hard, Put Away Wet",
      desc= "Jarate an enemy that you're dominating."},
    freezecam_hat ={ name= "Be Polite",
      desc= "Provide an enemy with a freezecam shot of you doffing your hat."},
    rifle_no_missing ={ name= "Be Efficient",
      desc= "Get 3 kills with the Sniper Rifle without missing a shot."},
    capture_flag ={ name= "Have a Plan",
      desc= "Capture the flag in CTF."},
    kill_grind ={ name= "Kill Everyone You Meet",
      desc= "Kill 1000 enemies."},
    kill_weapons ={ name= "Triple Prey",
      desc= "In a single round, get a kill with 3 different weapons."},
    headshot_snipers ={ name= "Self-destruct Sequence",
      desc= "Headshot 10 enemy Snipers."},
    destroy_sentryguns ={ name= "De-sentry-lized",
      desc= "Destroy 3 Engineer sentry guns."},
    kill_invis_spy ={ name= "Shoot the Breeze",
      desc= "Kill a fully invisible Spy in a single hit."},
    kill_midair_scout ={ name= "Dropped Dead",
      desc= "Kill a Scout in midair with your Sniper Rifle or the Huntsman."},
    freezecam_wave ={ name= "The Last Wave",
      desc= "Provide an enemy with a freezecam shot of you waving to them."},
    dominate_sniper ={ name= "Australian Rules",
      desc= "Dominate an enemy Sniper."},
    kill_spies_melee ={ name= "Kook the Spook",
      desc= "Kill 10 Spies with your Kukri."},
    headshot_demoman ={ name= "Socket to Him",
      desc= "Headshot an enemy Demoman."},
    kill_rjer ={ name= "Jumper Stumper",
      desc= "Kill a rocket or grenade-jumping enemy in midair with your Sniper Rifle or the Huntsman."},
    kill_objectives ={ name= "Not a Crazed Gunman, Dad",
      desc= "In a single life, kill 3 enemies while they are achieving an objective."},
    kill_unscoped ={ name= "Trust Your Feelings",
      desc= "Get 5 kills with the Sniper Rifle without your scope."},
    kill_charged_medic ={ name= "Überectomy",
      desc= "Kill a Medic that is ready to deploy an ÜberCharge."},
    get_backstabbed ={ name= "Consolation Prize",
      desc= "Get backstabbed 50 times."},
    kill_at_roundstart ={ name= "Enemy at the Gate",
      desc= "Kill an opponent within the first second of a round."},
    headshot_post_invuln ={ name= "Parting Shot",
      desc= "Headshot an enemy player the moment his invulnerability wears off."},
    top_scoreboard_grind ={ name= "My Brilliant Career",
      desc= "Top the scoreboard 10 times on teams of 6 or more players."},
    kill_failed_spy ={ name= "Shock Treatment",
      desc= "Kill a spy whose backstab attempt was blocked by your Razorback."},
    jarate_group ={ name= "Saturation Bombing",
      desc= "Jarate 4 enemy players with a single throw."},
    jarate_medic_pair ={ name= "Rain on Their Parade",
      desc= "Jarate an enemy and the Medic healing him."},
    jarate_reveal_spy ={ name= "Jarring Transition",
      desc= "Use Jarate to reveal a cloaked Spy."},
    jarate_extinguish ={ name= "Friendship is Golden",
      desc= "Extinguish a burning teammate with your Jarate."},
    bow_pin_heavy ={ name= "William Tell Overkill",
      desc= "Pin an enemy Heavy to the wall via his head."},
    bow_kill_medic_pair ={ name= "Beaux and Arrows",
      desc= "Kill a Heavy & Medic pair with the bow."},
    bow_kill_flagcarrier ={ name= "Robbin’ Hood",
      desc= "Take down an intelligence carrier with a single arrow."},
    bow_pincushion ={ name= "Pincushion",
      desc= "Hit an enemy with 3 arrows, without killing them."},
    jarate_assists ={ name= "Number One Assistant",
      desc= "Score 5 assists with the Jarate in a single round."},
    jarate_kill_melee ={ name= "Jarate Chop",
      desc= "Jarate and then kill 3 enemies with your Kukri."},
    taunt_kill ={ name= "Shafted",
      desc= "Stab an enemy with an arrow."},
    bow_kill_whiledead ={ name= "Dead Reckoning",
      desc= "Kill an enemy with an arrow while you're dead."},
    achieve_progress1 ={ name= "Sniper Milestone 1",
      desc= "Achieve 5 of the achievements in the Sniper pack."},
    achieve_progress2 ={ name= "Sniper Milestone 2",
      desc= "Achieve 11 of the achievements in the Sniper pack."},
    achieve_progress3 ={ name= "Sniper Milestone 3",
      desc= "Achieve 17 of the achievements in the Sniper pack."},
  },
  spy ={
    backstab_snipers ={ name= "Triplecrossed",
      desc= "Backstab 3 Snipers in a single life."},
    freezecam_flick ={ name= "For Your Eyes Only",
      desc= "Provide an enemy with a freezecam shot of you flicking a cigarette onto their corpse."},
    backstab_disguised_spy ={ name= "Counter Espionage",
      desc= "Backstab a disguised Spy."},
    backstab_disguise_target ={ name= "Identity Theft",
      desc= "Backstab the enemy that you're currently disguised as."},
    taunt_kill ={ name= "The Man from P.U.N.C.T.U.R.E.",
      desc= "Stab an enemy while fencing."},
    backstab_medic_healing_you ={ name= "FYI I am a Spy",
      desc= "Backstab a Medic who has healed you in the last 5 seconds."},
    backstab_engy_sap_building ={ name= "The Man with the Broken Guns",
      desc= "Backstab an Engineer, then sap 3 of his buildings within 10 seconds."},
    sap_building_backstab_engy ={ name= "Sapsucker",
      desc= "Sap an enemy building, then backstab the Engineer who built it within 5 seconds."},
    backstab_medic_pair ={ name= "May I Cut In?",
      desc= "Backstab an enemy and the Medic healing him within 10 seconds of each other."},
    backstab_friends ={ name= "Agent Provocateur",
      desc= "Backstab your Steam Community friends 10 times."},
    dominate_sniper ={ name= "The Melbourne Supremacy",
      desc= "Dominate a Sniper."},
    bump_cloaked_spy ={ name= "Spies Like Us",
      desc= "While cloaked, bump into an enemy cloaked Spy."},
    kill_spy_with_knife ={ name= "A Cut Above",
      desc= "Kill a gun-wielding Spy with your knife."},
    survive_burning ={ name= "Burn Notice",
      desc= "Survive 30 seconds after being ignited while cloaked."},
    break_shield_kill_sniper ={ name= "Die Another Way",
      desc= "Kill a Sniper after your backstab breaks his Razorback."},
    kill_working_engy ={ name= "Constructus Interruptus",
      desc= "Kill an Engineer who is working on a sentry gun."},
    fast_cap ={ name= "On Her Majesty’s Secret Surface",
      desc= "Start capping a capture point within a second of it becoming available."},
    medic_healing_kill_enemy ={ name= "Insurance Fraud",
      desc= "Kill an enemy while you're being healed by an enemy Medic."},
    kill_cp_defenders ={ name= "Point Breaker",
      desc= "Kill 15 enemies who are standing on a control point they own."},
    backstab_dominating_enemy ={ name= "High Value Target",
      desc= "Backstab an enemy who is dominating 3 or more of your teammates."},
    revenge_with_backstab ={ name= "Come in From the Cold",
      desc= "Get a Revenge kill with a backstab."},
    knife_kill_while_jarated ={ name= "Wetwork",
      desc= "Stab an enemy to death while under the influence of Jarate."},
    backstab_quick_kills ={ name= "You Only Shiv Thrice",
      desc= "Backstab 3 enemies within 10 seconds."},
    backstab_grind ={ name= "Spymaster",
      desc= "Backstab 1000 enemies."},
    sapper_grind ={ name= "Sap Auteur",
      desc= "Destroy 1000 Engineer buildings with sappers."},
    sapper_teamwork ={ name= "Joint Operation",
      desc= "Sap an enemy sentry gun within 3 seconds of a teammate sapping another."},
    backstab_medic_charged ={ name= "Dr. Nooooo",
      desc= "Backstab a Medic that is ready to deploy an ÜberCharge."},
    backstab_capping_enemies ={ name= "Is It Safe?",
      desc= "Backstab 50 enemies who are capturing control points."},
    backstab_enemy_switch_pyro ={ name= "Slash and Burn",
      desc= "Backstab an enemy, who then switches to Pyro before they respawn."},
    ambassador_grind ={ name= "Diplomacy",
      desc= "Kill 50 enemies with the Ambassador."},
    ambassador_sniper_grind ={ name= "Skullpluggery",
      desc= "Headshot 20 Snipers with the Ambassador."},
    feign_death_kill ={ name= "Sleeper Agent",
      desc= "Kill an enemy who triggered your feign death in the last 20 seconds."},
    ambassador_scout_grind ={ name= "Who's Your Daddy?",
      desc= "Headshot 3 Scouts with the Ambassador."},
    camp_position ={ name= "Deep Undercover",
      desc= "While using the Cloak and Dagger, kill the same enemy 3 times, all within the same area in a single life."},
    achieve_progress1 ={ name= "Spy Milestone 1",
      desc= "Achieve 5 of the achievements in the Spy pack."},
    achieve_progress2 ={ name= "Spy Milestone 2",
      desc= "Achieve 11 of the achievements in the Spy pack."},
    achieve_progress3 ={ name= "Spy Milestone 3",
      desc= "Achieve 17 of the achievements in the Spy pack."},
  },
  soldier ={
    achieve_progress1 ={ name= "Soldier Milestone 1",
      desc= "Achieve 5 of the achievements in the Soldier pack."},
    achieve_progress2 ={ name= "Soldier Milestone 2",
      desc= "Achieve 11 of the achievements in the Soldier pack."},
    achieve_progress3 ={ name= "Soldier Milestone 3",
      desc= "Achieve 17 of the achievements in the Soldier pack."},
    kill_group_with_crocket ={ name= "Tri-Splatteral Damage",
      desc= "Kill 3 enemies with a single critical rocket."},
    kill_two_during_rocket_jump ={ name= "Death from Above",
      desc= "Rocket jump and kill 2 enemies before you land."},
    three_dominations ={ name= "Dominator",
      desc= "Get 3 dominations in a single life."},
    defend_medic ={ name= "War Crime and Punishment",
      desc= "In a single life, kill 3 enemies who have damaged a Medic that is healing you."},
    kill_taunt ={ name= "Spray of Defeat",
      desc= "Use a grenade to gib a player."},
    destroy_sentry_out_of_range ={ name= "Guns of the Navar0wned",
      desc= "Kill 5 Engineer sentries while you are standing outside of their range."},
    kill_sniper_while_dead ={ name= "Mutually Assured Destruction",
      desc= "Kill an enemy sniper with a rocket after he kills you."},
    kill_airborne_target_while_airborne ={ name= "Wings of Glory",
      desc= "Kill an enemy soldier while both you and the target are airborne."},
    kill_engy ={ name= "Engineer to Eternity",
      desc= "Kill an Engineer as he repairs his sentry gun while it's under enemy fire."},
    nemesis_shovel_kill ={ name= "Trench Warfare",
      desc= "Kill your nemesis with a shovel."},
    destroy_stickies ={ name= "Bomb Squaddie",
      desc= "Destroy 10 sticky bombs with the shotgun in a single life."},
    crouch_rocket_jump ={ name= "Where Eagles Dare",
      desc= "Get the highest possible rocket jump using jump and crouch."},
    buff_friends ={ name= "Banner of Brothers",
      desc= "Buff 5 steam friends at once with the Buff Banner."},
    kill_twenty_from_above ={ name= "Screamin' Eagle",
      desc= "Kill 20 enemies from above."},
    shoot_mult_crits ={ name= "Crockets Are Such B.S.",
      desc= "Shoot two non-boosted crit rockets in a row."},
    kill_defenseless ={ name= "Geneva Contravention",
      desc= "Kill 5 defenseless players after a single match has ended."},
    kill_on_fire ={ name= "Semper Fry",
      desc= "Kill 20 enemies while you are on fire."},
    kill_five_stunned ={ name= "The Longest Daze",
      desc= "Kill 5 stunned players."},
    freezecam_gibs ={ name= "Gore-a! Gore-a! Gore-a!",
      desc= "Provide the enemy with a freezecam of you taunting over 3 of their body parts."},
    kill_spy_killer ={ name= "War Crime Spybunal",
      desc= "Kill a Spy who just backstabbed a teammate."},
    defend_cap_thirty_times ={ name= "Hamburger Hill",
      desc= "Defend a cap point 30 times."},
    gib_grind ={ name= "Frags of our Fathers",
      desc= "Gib 1000 people."},
    rj_equalizer_kill ={ name= "Duty Bound",
      desc= "While rocket jumping kill an enemy with the Equalizer before you land."},
    buff_teammates ={ name= "The Boostie Boys",
      desc= "Buff 15 teammates with the Buff Banner in a single life."},
    kill_demoman_grind ={ name= "Out, Damned Scot!",
      desc= "Kill 500 enemy Demomen"},
    kill_pyro ={ name= "Backdraft Dodger",
      desc= "Kill a Pyro who has airblasted one of your rockets in the last 10 seconds."},
    equalizer_streak ={ name= "Ain't Got Time to Bleed",
      desc= "Kill 3 players with the Equalizer in a single life without being healed."},
    kill_with_equalizer_while_hurt ={ name= "Near Death Experience",
      desc= "Kill 20 enemies with your Equalizer while you have less than 25 health."},
    bounce_then_shotgun ={ name= "For Whom the Shell Trolls",
      desc= "Bounce an opponent into the air with a rocket and then kill them with the shotgun before they land."},
    kill_airborne_with_direct_hit ={ name= "Death From Below",
      desc= "Kill 10 opponents who are airborne with the Direct Hit."},
    freezecam_taunt ={ name= "Worth a Thousand Words",
      desc= "Provide the enemy with a freezecam of your 21 gun salute."},
    duo_soldier_kills ={ name= "Brothers in Harms",
      desc= "Kill 10 enemies while assisting or being assisted by another Soldier."},
    mvp ={ name= "Medals of Honor",
      desc= "Finish a round as an MVP on a team of 6 or more players 10 times."},
    ride_the_cart ={ name= "Ride of the Valkartie",
      desc= "Ride the cart for 30 seconds."},
    assist_medic_uber ={ name= "S*M*A*S*H",
      desc= "Assist a Medic in exploding 5 enemies with a single ÜberCharge."},
  },
  demoman ={
    kill_soldier_grind ={ name= "Kilt in Action",
      desc= "Kill 500 enemy Soldiers"},
    destroy_buildings_with_medic ={ name= "Tam O'Shatter",
      desc= "Destroy 5 enemy Engineer buildings during a single ÜberCharge from a Medic."},
    decapitate_cloaked_spy ={ name= "Shorn Connery",
      desc= "Decapitate a cloaked Spy."},
    kill_x_with_directpipe ={ name= "Laddy Macdeth",
      desc= "Kill 50 enemies with direct hits from the Grenade Launcher."},
    bounce_and_kill ={ name= "Caber Toss",
      desc= "Bounce an enemy into the air and kill them before they land."},
    decapitate_players ={ name= "Brainspotting",
      desc= "Decapitate 50 enemy players."},
    decapitate_players_fast ={ name= "Left 4 Heads",
      desc= "Decapitate 4 players with only 10 seconds between each kill."},
    duo_demoman_kills ={ name= "Well Plaid!",
      desc= "Kill 10 enemies while assisting or being assisted by another Demoman."},
    kill_two_during_stickyjump ={ name= "Double Mauled Scotch",
      desc= "Kill 2 people in a single sticky jump."},
    kill_player_after_tp ={ name= "Loch Ness Bombster",
      desc= "Kill an enemy player with sticky bombs within 5 seconds of them teleporting."},
    dominate_three_engineers ={ name= "Three Times a Laddy",
      desc= "Dominate 3 Engineers."},
    kill_building_direct_hit ={ name= "Blind Fire",
      desc= "Destroy an Engineer building that you can't see with a direct hit from your Grenade Launcher."},
    melee_kill_while_stickyjumping ={ name= "The Scottish Play",
      desc= "Get a melee kill while sticky jumping."},
    kill_engi_sentry_dispenser ={ name= "The Argyle Sap",
      desc= "Blow up an Engineer, his sentry gun, and his dispenser with a single Sticky bomb detonation."},
    decapitate_equalizer ={ name= "Slammy Slayvis Woundya",
      desc= "Decapitate an enemy Soldier who is brandishing the Equalizer."},
    decapitate_nemesis ={ name= "There Can Be Only One",
      desc= "Decapitate your nemesis."},
    damage_grind ={ name= "Tartan Spartan",
      desc= "Do 1 million points of total blast damage."},
    kill_x_capping_onedet ={ name= "Scotch Guard",
      desc= "Kill 3 enemies capping or pushing a cart in a single Stickybomb detonation 3 separate times."},
    kill_x_defending ={ name= "Bravehurt",
      desc= "Kill 25 players defending a capture point or cart."},
    destroy_buildings_grind ={ name= "Cry Some Moor!",
      desc= "Destroy 50 buildings."},
    kill_x_heavies_fullhp_onedet ={ name= "The Stickening",
      desc= "Kill 5 Heavies from full health with a single sticky bomb detonation."},
    kill_x_scouts_pyros ={ name= "Glasg0wned",
      desc= "Kill 25 Scouts and Pyros with the Grenade Launcher."},
    taunt_kill ={ name= "Scotch Tap",
      desc= "Glory in the slaughter of your enemies using the Eyelander."},
    charge_kill ={ name= "The Targe Charge",
      desc= "Charge and kill someone with your shield bash."},
    crit_sword_kill ={ name= "Beat Me Up, Scotty",
      desc= "Use a critical swing with the Eyelander to kill 5 enemy players."},
    air_burst_kills ={ name= "Something Stickied This Way Comes",
      desc= "Kill 30 players with air burst sticky bombs."},
    stickyjump_cap ={ name= "The High Road",
      desc= "Sticky jump onto a cap point and capture it."},
    freezecam_smile ={ name= "Bloody Merry",
      desc= "Provide an enemy player with a freeze cam of your smiling face."},
    freezecam_rump ={ name= "Second Eye",
      desc= "Provide an enemy player with a freeze cam of you shaking your rump."},
    environmental_kill ={ name= "He Who Celt It",
      desc= "Use the Sticky Launcher to kill an enemy player via environmental damage."},
    destroy_x_stickybombs ={ name= "Robbed Royal",
      desc= "Destroy 100 enemy sticky bombs with the Scottish Resistance."},
    stickjump_distance ={ name= "Highland Fling",
      desc= "Sticky jump a really long way..."},
    kill3_with_detonation ={ name= "Pipebagger",
      desc= "Kill at least three players with a single detonation of sticky bombs."},
    killxsappingspies ={ name= "Spynal Tap",
      desc= "Kill 20 spies within 5 seconds of them sapping a friendly building."},
    kill3_with_pipe_setups ={ name= "Sticky Thump",
      desc= "Using the Scottish Resistance, kill 3 players in separate explosions without placing new sticky bombs."},
    achieve_progress1 ={ name= "Demoman Milestone 1",
      desc= "Achieve 5 of the achievements in the Demoman pack."},
    achieve_progress2 ={ name= "Demoman Milestone 2",
      desc= "Achieve 11 of the achievements in the Demoman pack."},
    achieve_progress3 ={ name= "Demoman Milestone 3",
      desc= "Achieve 17 of the achievements in the Demoman pack."},
  },
  engineer ={
    achieve_progress1 ={ name= "Engineer Milestone 1",
      desc= "Achieve 5 of the achievements in the Engineer pack."},
    achieve_progress2 ={ name= "Engineer Milestone 2",
      desc= "Achieve 11 of the achievements in the Engineer pack."},
    achieve_progress3 ={ name= "Engineer Milestone 3",
      desc= "Achieve 17 of the achievements in the Engineer pack."},
    teleport_grind ={ name= "Battle Rustler",
      desc= "Teleport 100 team members into battle."},
    dispenser_extinguish ={ name= "The Extinguished Gentleman",
      desc= "Have dispensers you built extinguish 20 burning players."},
    revenge_crit_sentry_killer ={ name= "Revengineering",
      desc= "Use a revenge crit to kill the enemy player that destroyed your sentry gun."},
    manual_cloaked_spy_kill ={ name= "Search Engine",
      desc= "Kill 3 cloaked Spies with a sentry gun under control of your Wrangler."},
    manual_sentry_kills_beyond_range ={ name= "Pownd on the Range",
      desc= "Kill 10 enemies outside the normal sentry gun range using the Wrangler."},
    manual_sentry_absorb_dmg ={ name= "Building Block",
      desc= "Have a sentry shielded by the Wrangler absorb 500 damage without being destroyed."},
    revenge_crit_life ={ name= "Unforgiven",
      desc= "Kill 3 enemies with revenge crits without dying."},
    kill_spy_two_sappers ={ name= "Quick Draw",
      desc= "Kill a spy and two sappers within 10 seconds."},
    kill_disguised_spy ={ name= "The Wrench Connection",
      desc= "Kill a disguised spy with your Wrench."},
    upgrade_buildings ={ name= "Silent Pardner",
      desc= "Upgrade 50 buildings built by other team members."},
    destroy_sappers ={ name= "Fistful of Sappers",
      desc= "Destroy 25 sappers on buildings built by other team members."},
    repair_sentry_w_medic ={ name= "Doc, Stock, and Barrel",
      desc= "Repair a sentry gun under fire while being healed by a Medic."},
    sentry_kill_lifetime_grind ={ name= "Best Little Slaughterhouse in Texas",
      desc= "Rack up 5000 kills with your sentry guns."},
    sentry_avenges_you ={ name= "Frontier Justice",
      desc= "Have your sentry kill the enemy that just killed you within 10 seconds."},
    freezecam_taunt ={ name= "Six-String Stinger",
      desc= "Provide an enemy player with a freeze cam of your guitar playing skills."},
    freezecam_sentry ={ name= "Uncivil Engineer",
      desc= "Provide an enemy player with a freeze cam of you and the sentry that just killed them."},
    shotgun_kill_prev_sentry_target ={ name= "Texas Two-Step",
      desc= "Use your shotgun to finish off an enemy recently damaged by your sentry gun."},
    dispenser_heal_group ={ name= "Doc Holiday",
      desc= "Have a dispenser heal 3 teammates at the same time."},
    sentry_kill_caps ={ name= "No Man's Land",
      desc= "Use a sentry gun to kill 25 enemy players that are capturing a point."},
    kill_flag_carriers ={ name= "Trade Secrets",
      desc= "Kill 20 players carrying the intelligence."},
    waste_metal_grind ={ name= "Death Metal",
      desc= "Pick up 10,000 waste metal from pieces of destroyed buildings."},
    help_build_structure ={ name= "Land Grab",
      desc= "Help a teammate construct a building."},
    remove_sapper_long_dist ={ name= "Get Along!",
      desc= "Manage to get to and then remove a sapper placed on your building while you were several meters away."},
    destroy_stickies ={ name= "How the Pests Was Gunned",
      desc= "Destroy 50 enemy stickybombs lying in range of friendly buildings."},
    taunt_kill ={ name= "Honky Tonk Man",
      desc= "Smash an enemy player's head in with your guitar."},
    kill_snipers_sentry ={ name= "Breaking Morant",
      desc= "Kill 10 Snipers with a sentry gun under control of your Wrangler."},
    help_manual_sentry ={ name= "Rio Grind",
      desc= "Perform 50 repairs and/or reloads on a Sentry gun being Wrangled by another Engineer."},
    kill_sentry_with_sentry ={ name= "Patent Protection",
      desc= "Destroy an enemy Engineer's sentry gun with a sentry under control of your Wrangler."},
    move_sentry_get_kill ={ name= "If You Build It, They Will Die",
      desc= "Haul a level 3 sentry gun into a position where it achieves a kill shortly after being redeployed."},
    building_carry ={ name= "Texas Ranger",
      desc= "Haul buildings 1 km over your career."},
    kill_assist ={ name= "Deputized",
      desc= "Get 10 assists with another Engineer where a sentry gun was involved in the kill."},
    dispenser_heal_grind ={ name= "Drugstore Cowboy",
      desc= "Have dispensers you created dispense a combined amount of 100,000 health over your career."},
    repair_team_grind ={ name= "Circle the Wagons",
      desc= "Repair 50,000 damage to friendly buildings constructed by other players."},
    tank_damage ={ name= "Built to Last",
      desc= "Help a single building tank over 2000 damage without being destroyed."},
    heavy_assist ={ name= "(Not So) Lonely Are the Brave",
      desc= "Keep a Heavy healed with your dispenser while he gains 5 kills."},
  },
}

return tf
