--This file lists tweaks made to minor details in VectorMagic
--between importing the raster image and exporting the SVG.

tweaks={
  medic={
    AutopsyReport={
      colors=2},
    ChiefOfStaff={
      create="Left glasses orange seepthrough"},
    DoesItHurtWhenIDoThis={
      colors=2,
      separate="Rightmost tooth"},
    DoubleBlindTrial={
      separate="Right Medic inner ear",
      forced_cutout=true},
    FamilyPractice={
      merge="Bottom Medic's hand (gripping Spy)",
      carve="Bottom Medic's coat tail separator"},
    FYIIAmAMedic={
      special="Photograph settings"},
    Intern={
      merge="Background under base of plunger of topmost syringe"},
    PeerReview={
      colors=2},
    PlaceboEffect={
      smooth="Left side of Medic"},
    TraumaQueen={
      smooth="Smallest ripple on left"},
  },
  pyro={
    barbequeq={
      colors=2},
    combined_fire={
      colors=2},
    dance_dance_immolation={
      colors=5,
      zap="Around tank of white Pyro's flamethrower",
      create="Darker orange section under head of brightest Pyro",
      carve="Darker orange hose by brighter orange"},
    i_fry={
      unite="Right side of nose (touch middle part with diagonal pixel)"},
    pyro_achieve_progress2={
      zap="bottom of middle balloon's string"},
    pyro_achieve_progress2={
      special="Essentially the same as tf_heavy_achieve_progress3"},
    pyromancer={
      colors=6},
    spontaneous_combustion={
      colors=2},
    trailblazer={
      smooth="Bottom of top ring"},
  },
  heavy={
    tf_heavy_achieve_progress2={
      fill="Bottom of middle balloon string"},
    tf_heavy_assist_grind={
      colors=2},
    tf_heavy_block_invuln_heavy={
      colors=2},
    tf_heavy_clear_stickybombs={
      zap="Middle and bottom spikes on right side"},
    tf_heavy_defend_medic={
      colors=2},
    tf_heavy_eat_sandwiches={
      colors=2},
    tf_heavy_fire_lots={
      colors=2},
    tf_heavy_kill_midair_minigun={
      smooth="Bottom of Medic's glove"},
    tf_heavy_kill_midair_minigun={
      colors=2},
    tf_heavy_kill_shotgun={
      colors=2},
--  tf_heavy_kill_underwater={
--    create="Little bit to the left of the bottom fin"},
    tf_heavy_payload_cap_grind={
      colors=2},
    tf_heavy_stand_near_dispenser={
      colors=2},
    tf_heavy_survive_crocket={
      colors=2},
    tf_heavy_uncover_spies={
      colors=2},
  },
  scout={
    artful_dodger={
      colors=2},
    block_the_plate={
      zap="Top of fold in hand that's a lighter gray in the original",
      smooth="Bottom-left of middle ring on plate"},
    brushback={
      merge="Bottom of bottom rivet on bomb casing"},
    caught_napping={
      colors=2},
    doctoring_the_ball={
      create="Right eye",
      merge="Top of glow"},
    first_blood={
      merge="Lightning above head"},
    first_blood_part_2={
      expand="Leftmost spot",
      create="Tick nearest tip",
      merge="Line on right side of bat"},
    gun_down={
      colors=2},
    if_you_build_it={
      colors=2},
    im_bat_man={
      colors=2},
    pop_fly={
      zap="Inside of left burst's top ray"},
    race_for_the_pennant={
      colors=4},
    round_tripper={
      colors=2},
    set_the_table={
      colors=5,
      expand="Hat brims on darker colors"},
    side_retired={
      zap="Topmost plate",
      merge="Rings",
      separate="Rings"},
    tf_scout_achieve_progress2={
      fill="Bottom of middle balloon string"},
    triple_play={
      colors=4,
      merge="Second ring on back plate"},
    triple_steal={
      colors=2},
  },
  sniper={
    tf_sniper_australian_rules={
      colors="unlimited"},
    tf_sniper_be_polite={
      carve="Folds inside hat, jowl, top of thing on back",
      expand="White on lower side of strap",
      separate="head and neck"},
    tf_sniper_beaux_and_arrows={
      colors=5,
      manual_palette="Get top and second-row crosses"},
    tf_sniper_consolation_prize={
      separate="right screw",
      create="top part of below-rightmost tab on ribbon"},
    ["tf_sniper_de-sentry-lized"]={
      separate="Hinge and body"},
    tf_sniper_enemy_at_the_gate={
      colors=4},
    tf_sniper_friendship_is_golden={
      colors=4},
    tf_sniper_jarate_chop={
      colors=5},
    tf_sniper_jarring_transition={
      colors=5},
    tf_sniper_jumper_stumper={
      merge="back of skirt thing",
      separate="right grenade"},
    tf_sniper_kill_everyone_you_meet={
      create="lenscap, scope, sleeve details"},
    tf_sniper_kook_the_spook={
      separate="Spots on collar",
      zap="Top edge of kukri",
      create="Right fold of collar, spot on left side of collar",
      smooth="Top-right side of eye hole"},
    tf_sniper_my_brilliant_career={
      separate="Bottom-left spot on #",
      expand="Bottom-left spot on #, spots on left side of 1",
      create="Spots in other 2 quadrants of #"},
    tf_sniper_not_a_crazed_gunman_dad={
      smooth="Underside of Pyro tank"}, --artifacts?
    tf_sniper_number_one_assistant={
      colors=6},
    tf_sniper_parting_shot={
      colors=5,
      create="Third figure's arm near tip of orange figure's high hand"},
    tf_sniper_pincushion={
      colors=8,
      manual_palette="Brown, stubble, highlight line on chin, lower 3 bullets, bottom of nose",
      zap="behind ear",
      fill="grey parts of eyes to brown",
      create="light orange part of back collar, parts of wrap on nearby arrow and by ear"},
    tf_sniper_rain_on_their_parade={
      zap="right line in Medic",
      create="line on Demoman's cheek, lines on Medic's face",
      separate="eyebrow and eyepatch,Medic top lip and front teeth"},
    tf_sniper_robbin_hood={
      create="arrow wraps",
      separate="bottom of papers on right"},
    tf_sniper_shafted={
      colors=4},
    tf_sniper_socket_to_him={
      colors=4},
    tf_sniper_uberectomy={
      colors=4},
    tf_sniper_william_tell_overkill={
      colors=4},
  },
  spy={
    tf_spy_a_cut_above={
      separate="middle of gun",
      zap="orange at clasp of knife"},
    tf_spy_burn_notice={
      colors=5},
    tf_spy_come_in_from_the_cold={
      colors=5,
      merge="Heavy eyelid, fabric around second-to-bottom button",
      fill="Heavy eye,middle of line on head, bottom of patch outline",
      zap="Orange at top of knife clasp"},
    tf_spy_constructus_interruptus={
      separate="Index fingertip, middle of wrench, top segment of arm from pool",
      create="indentation in mid-wrench"},
    tf_spy_diplomacy={
      colors=5,
      unite="rings at muzzle"},
    tf_spy_for_your_Eyes_only={
      zap="base of cigarette"},
    tf_spy_high_value_target={
      separate="Bottom/right screw from surroundings"},
    tf_spy_identity_theft={
      fix="Top of globe"},
    tf_spy_insurance_fraud={
      colors=5,
      manual_palette="Top cross and bottom cross are slightly different shades",
      zap="near latch"},
    tf_spy_is_it_safe={
      create="smoke trail, line on knife"},
    tf_spy_slash_and_burn={
      extend="lines from body",
      create="lines around pouch"},
    tf_spy_sleeper_agent={
      create="line on knife",
      marge="lower crack coming from P"},
    tf_spy_spies_like_us={
      colors=5,
      fill="between left Spy's legs",
      create="suit folds",
      zap="left spy left collar"},
    tf_spy_spymaster={
      create="bottom of knife line",
      merge="knuckle of middle and pinky fingers"},
    tf_spy_the_man_from_puncture={
      colors=5,
      create="back Spy's knife",
      fill="space between orange and darker spy's arms, line in middle of front Spy at bottom of jacket"},
    tf_spy_the_melbourne_supremacy={
      create="gaps in splat",
      zap="clasp"},
    tf_spy_triple_crossed={
      zap="Left and right clasps"},
    tf_spy_whos_your_daddy={
      zap="clasp"},
    tf_spy_you_only_shiv_thrice={
      zap="left side of clock part between 1 and 0",
      smooth="middle knife line",
      create="right knife line",
      separate="Left index finger from hand",
      merge="right pinky"},
  },
  soldier={
    tf_soldier_achieve_progress2={
      special="It's just the Scout icon with JPEG compression artifacts..."},
    tf_soldier_aint_got_time_to_bleed={
      colors=4},
    tf_soldier_backdraft_dodger={
      colors=4},
    tf_soldier_banner_of_brothers={
      colors=4},
    tf_soldier_bomb_squaddie={
      colors=4},
    tf_soldier_crockets_are_such_bs={
      colors=4,
      separate="tip of left rocket, base of right"},
    tf_soldier_death_from_above={
      colors=4,
      zap="under 5th feather on left wing"},
    tf_soldier_dominator={
      colors=4},
    tf_soldier_duty_bound={
      fill="hole that's technically in the original in blast",
      zap="right wingtip, left highest indentation, left low triangle"},
    tf_soldier_frags_of_our_fathers={
      colors=5},
    tf_soldier_geneva_contravention={
      colors=4,
      cheate="cheekbones, neckline"},
    tf_soldier_gomer_pileon={
      colors=4},
    tf_soldier_gora_gora_gora={
      colors=4},
    tf_soldier_guns_of_navar0wnedt={
      colors=4,
      create="hinge left line"},
    tf_soldier_hamburger_hill={
      colors=5,
      fill="mouth (white)",
      separate="torso from belt"},
    tf_soldier_mashed={
      create="orange above 5"},
    tf_soldier_metals_of_honor={
      colors=4},
    tf_soldier_mutually_assured_destruction={
      colors=5},
    tf_soldier_out_damned_scot={
      colors=4},
    tf_soldier_screamin={
      create="inside 2 rocket segment"},
    tf_soldier_semper_fry={
      colors=5},
    tf_soldier_spray_of_defeat={
      colors=4},
    tf_soldier_the_boostie_boys={
      colors=4},
    tf_soldier_the_longest_gaze={
      colors=4},
    tf_soldier_trench_warfare={
      colors=5},
    tf_soldier_trisplatteral_damage={
      colors=5},
    tf_soldier_war_crime_and_punnishment={
      colors=4},
    tf_soldier_war_crime_spybunal={
      add="Shoulder lines"},
    tf_soldier_wings_of_glory={
      colors=4,
      zap="most of the right wing's edge"},
    tf_soldier_worth_a_thousand_wars={
  },
  demoman={
    tf_demo_achieve_progress2={
      zap="Bottom of middle balloon string"},
    tf_demoman_bounce_and_kill={
      zap="Inside of left burst's top ray"},
    tf_demoman_charge_kill={
      create="lines on right side of targe, line in upper left"},
    tf_demoman_decapitate_nemesis={
      create="line to right on hilt"},
    tf_demoman_decapitate_players={
      fill="Right side of Scout neck"},
    tf_demoman_destroy_buildings_with_medic={
      colors=2},
    tf_demoman_destroy_x_stickybombs={
      zap="Middle and bottom spikes on right side"},
    tf_demoman_freezecam_smile={
      colors=2},
    tf_demoman_kill_x_defending={
      colors=2},
    tf_demoman_taunt_kill={
      colors=2},
    tf_demoman_kill_player_after_tp={
      smooth="tip of top-right spike"},
    tf_demoman_kill_two_during_stickyjump={
      zap="Inside of left burst's top ray"},
    tf_demoman_killxsappingspies={
      merge="bottom-right corner"},
  },
  engineer={
    breaking_morant={
      fill="Right jowl",
      unite="Right jowl line"},
    engineer_progress2={
      zap="Bottom of middle balloon string",
      separate="Left balloon neck"},
    frontier_justice={
      carve="hole in middle of spatter"},
    git_along={
      separate="Right switch",
      merge="Middle of lines, left screw"},
    no_so_lonely_are_the_brave={
      separate="dispenser hand from edge"},
    patent_protection={
      colors=2},
    pownd_on_the_range={
      zap="Orange rim around left foot"},
    search_engine={
      create="Line down from hand",
      separate="Most spots from lines"},
    six_string_stinger={
      separate="Top of goggles from brim",
      zap="Left side of photo"},
    the_extinugished_gentleman={
      create="Middles of side handles",
      smooth="Side of dispenser",
      separate="Thing on tank"},
    the_wrench_connection={
      extend="left nostril"},
    trade_secrets={
      separate="Bottom corner of papers",
      zap="orange around right white circle"},
    unforgiven={
      colors=2},
  },
}
--CHECK SHAPE MODE IN EXPORT OPTIONS BEFORE SAVING!
