--encoding: utf-8
--same reasons as the output file

achievements={
--[[// Achievements
"TF_GET_TURRETKILLS_NAME"		"Sentry Gunner"
"TF_GET_TURRETKILLS_DESC"		"Accumulate 10 sentry gun kills with a single sentry."
"TF_KILL_NEMESIS_NAME"			"Nemesis"
"TF_KILL_NEMESIS_DESC"			"Get five revenge kills."
"TF_GET_CONSECUTIVEKILLS_NODEATHS_NAME"	"Hard to Kill"
"TF_GET_CONSECUTIVEKILLS_NODEATHS_DESC"	"Get five kills in a row without dying."
"TF_GET_HEALED_BYENEMY_NAME"		"Master of Disguise"
"TF_GET_HEALED_BYENEMY_DESC"		"Trick an opposing Medic into healing you."
"TF_GET_HEADSHOTS_NAME"			"Grey Matter"
"TF_GET_HEADSHOTS_DESC"			"Get 25 headshots as a Sniper."
"TF_PLAY_GAME_FRIENDSONLY_NAME"		"With Friends Like these..."
"TF_PLAY_GAME_FRIENDSONLY_DESC"		"Play in a game with 7 or more players from your friends list."
"TF_WIN_MULTIPLEGAMES_NAME"		"Dynasty"
"TF_WIN_MULTIPLEGAMES_DESC"		"Win 20 games."
"TF_GET_MULTIPLEKILLS_NAME"		"Hardcore"
"TF_GET_MULTIPLEKILLS_DESC"		"Accumulate 1000 total kills."
"TF_WIN_2FORT_NOENEMYCAPS_NAME"		"Powerhouse Offense"
"TF_WIN_2FORT_NOENEMYCAPS_DESC"		"Win 2Fort with a shutout."
"TF_WIN_WELL_MINIMUMTIME_NAME"		"Lightning Offense"
"TF_WIN_WELL_MINIMUMTIME_DESC"		"Win Well in 5 minutes or less."
"TF_WIN_HYDRO_NOENEMYCAPS_NAME"		"Relentless Offense"
"TF_WIN_HYDRO_NOENEMYCAPS_DESC"		"Win Hydro without giving up a capture."
"TF_WIN_DUSTBOWL_NOENEMYCAPS_NAME"	"Impenetrable Defense"
"TF_WIN_DUSTBOWL_NOENEMYCAPS_DESC"	"Successfully defend Dustbowl without giving up a capture."
"TF_WIN_GRAVELPIT_NOENEMYCAPS_NAME"	"Impossible Defense"
"TF_WIN_GRAVELPIT_NOENEMYCAPS_DESC"	"Successfully defend Gravel Pit without giving up a capture."
"TF_PLAY_GAME_EVERYCLASS_NAME"		"Head of the Class"
"TF_PLAY_GAME_EVERYCLASS_DESC"		"Play a complete round with every class."
"TF_PLAY_GAME_EVERYMAP_NAME"		"World Traveler"
"TF_PLAY_GAME_EVERYMAP_DESC"		"Play a complete game on 2Fort, Dustbowl, Granary, Gravel Pit, Hydro, and Well (CP)."
"TF_GET_HEALPOINTS_NAME"		"Team Doctor"
"TF_GET_HEALPOINTS_DESC"		"Accumulate 25000 heal points as a Medic."
"TF_BURN_PLAYERSINMINIMUMTIME_NAME"	"Flamethrower"
"TF_BURN_PLAYERSINMINIMUMTIME_DESC"	"Set five enemies on fire in 30 seconds."
]]

medic=[[
"TF_MEDIC_TOP_SCOREBOARD_NAME"	"First Do No Harm"
"TF_MEDIC_TOP_SCOREBOARD_DESC"	"Play a full round without killing any enemies, and score the highest on a team of 6 or more players."
"TF_MEDIC_HEAL_UNDER_FIRE_NAME"	"Quadruple Bypass"
"TF_MEDIC_HEAL_UNDER_FIRE_DESC"	"Heal a teammate who's taking fire from 4 enemies at once."
"TF_MEDIC_SIMUL_CHARGE_NAME"	"Group Health"
"TF_MEDIC_SIMUL_CHARGE_DESC"	"Work with 2 other Medics to deploy 3 simultaneous ÜberCharges."
"TF_MEDIC_SETUP_CHARGE_NAME"	"Surgical Prep"
"TF_MEDIC_SETUP_CHARGE_DESC"	"Have an ÜberCharge ready before the Setup phase ends."
"TF_MEDIC_RAPID_CHARGE_NAME"	"Trauma Queen"
"TF_MEDIC_RAPID_CHARGE_DESC"	"Deploy 3 ÜberCharges in less than 5 minutes, and assist in 5 kills during that time."
"TF_MEDIC_COUNTER_CHARGE_NAME"	"Double Blind Trial"
"TF_MEDIC_COUNTER_CHARGE_DESC"	"Deploy an ÜberCharge within 8 seconds of a nearby enemy Medic deploying his."
"TF_MEDIC_SWITCH_TO_MEDIC_NAME"	"Play Doctor"
"TF_MEDIC_SWITCH_TO_MEDIC_DESC"	"In a team with no Medics, be the first person to switch to Medic after a teammate calls for 'Medic!', and then heal 500 health."
"TF_MEDIC_SAVE_TEAMMATE_NAME"	"Triage"
"TF_MEDIC_SAVE_TEAMMATE_DESC"	"Deploy an ÜberCharge on a teammate less than a second before they're hit by a critical explosive."
"TF_MEDIC_CHARGE_BLOCKER_NAME"	"Preventive Medicine"
"TF_MEDIC_CHARGE_BLOCKER_DESC"	"Block the enemy from capturing a control point with an ÜberCharged teammate."
"TF_MEDIC_ASSIST_MEDIC_NAME"	"Consultation"
"TF_MEDIC_ASSIST_MEDIC_DESC"	"Assist a fellow Medic in killing 5 enemies in a single life."
"TF_MEDIC_SYRINGE_SCOUTS_NAME"	"Does It Hurt When I Do This?"
"TF_MEDIC_SYRINGE_SCOUTS_DESC"	"Kill 50 Scouts with your syringe gun."
"TF_MEDIC_BONESAW_MEDICS_NAME"	"Peer Review"
"TF_MEDIC_BONESAW_MEDICS_DESC"	"Kill 50 Medics with your bone saw."
"TF_MEDIC_ASSIST_HEAVY_LONG_NAME"	"Big Pharma"
"TF_MEDIC_ASSIST_HEAVY_LONG_DESC"	"Assist a Heavy in killing 10 enemies, where neither of you die."
"TF_MEDIC_ASSIST_SCOUT_NAME"	"You'll Feel a Little Prick"
"TF_MEDIC_ASSIST_SCOUT_DESC"	"Assist in killing 3 enemies with a single ÜberCharge on a Scout."
"TF_MEDIC_ASSIST_PYRO_NAME"		"Autoclave"
"TF_MEDIC_ASSIST_PYRO_DESC"		"Assist in burning 5 enemies with a single ÜberCharge on a Pyro."
"TF_MEDIC_ASSIST_HEAVY_NAME"	"Blunt Trauma"
"TF_MEDIC_ASSIST_HEAVY_DESC"	"Assist in punching 2 enemies with a single ÜberCharge on a Heavy."
"TF_MEDIC_ASSIST_DEMOMAN_NAME"	"Medical Breakthrough"
"TF_MEDIC_ASSIST_DEMOMAN_DESC"	"Assist in destroying 5 enemy Engineer buildings with a single ÜberCharge on a Demoman."
"TF_MEDIC_ASSIST_SOLDIER_NAME"	"Blast Assist"
"TF_MEDIC_ASSIST_SOLDIER_DESC"	"Assist in exploding 5 enemies with a single ÜberCharge on a Soldier."
"TF_MEDIC_HEAL_ENGINEER_NAME"	"Midwife Crisis"
"TF_MEDIC_HEAL_ENGINEER_DESC"	"Heal an Engineer as he repairs his sentry gun while it's under enemy fire."
"TF_MEDIC_ASSIST_CAPTURER_NAME"	"Ubi concordia, ibi victoria"
"TF_MEDIC_ASSIST_CAPTURER_DESC"	"Assist in killing 3 enemies on an enemy control point, in a single life."
"TF_MEDIC_HEAL_CALLERS_NAME"	"Grand Rounds"
"TF_MEDIC_HEAL_CALLERS_DESC"	"Heal 200 teammates after they've called for 'Medic!'."
"TF_MEDIC_EXTINGUISH_TEAMMATES_NAME"	"Infernal Medicine"
"TF_MEDIC_EXTINGUISH_TEAMMATES_DESC"	"Extinguish 100 burning teammates."
"TF_MEDIC_ASSIST_VS_NEMESES_NAME"	"Doctor Assisted Homicide"
"TF_MEDIC_ASSIST_VS_NEMESES_DESC"	"Assist in killing 20 nemeses."
"TF_MEDIC_KILL_WHILE_CHARGED_NAME"	"Placebo Effect"
"TF_MEDIC_KILL_WHILE_CHARGED_DESC"	"Kill 5 enemies in a single life, while having your ÜberCharge ready, but undeployed."
"TF_MEDIC_BONESAW_NOMISSES_NAME"	"Sawbones"
"TF_MEDIC_BONESAW_NOMISSES_DESC"	"Hit enemies with your bonesaw 5 times in a row without dying or missing."
"TF_MEDIC_HEAL_LARGE_NAME"	"Intern"
"TF_MEDIC_HEAL_LARGE_DESC"	"Accumulate 7000 heal points in a single life."
"TF_MEDIC_HEAL_HUGE_NAME"	"Specialist"
"TF_MEDIC_HEAL_HUGE_DESC"	"Accumulate 10000 heal points health in a single life."
"TF_MEDIC_HEAL_GRIND_NAME"	"Chief of Staff"
"TF_MEDIC_HEAL_GRIND_DESC"	"Accumulate 1 million total heal points."
"TF_MEDIC_KILL_HEALED_SPY_NAME"	"Hypocritical Oath"
"TF_MEDIC_KILL_HEALED_SPY_DESC"	"Kill an enemy Spy that you have been healing."
"TF_MEDIC_SAVE_FALLING_TEAMMATE_NAME"	"Medical Intervention"
"TF_MEDIC_SAVE_FALLING_TEAMMATE_DESC"	"Save a falling teammate from dying on impact."
"TF_MEDIC_CHARGE_JUGGLE_NAME"	"Second Opinion"
"TF_MEDIC_CHARGE_JUGGLE_DESC"	"ÜberCharge 2 teammates at once."
"TF_MEDIC_FREEZECAM_RAGDOLL_NAME"	"Autopsy Report"
"TF_MEDIC_FREEZECAM_RAGDOLL_DESC"	"Provide an enemy with a freezecam shot of you taunting above their ragdoll."
"TF_MEDIC_BONESAW_SPY_CALLERS_NAME"	"FYI I am A Medic"
"TF_MEDIC_BONESAW_SPY_CALLERS_DESC"	"Use your bonesaw to kill 5 Spies who have been calling for 'Medic!'."
"TF_MEDIC_CHARGE_FRIENDS_NAME"	"Family Practice"
"TF_MEDIC_CHARGE_FRIENDS_DESC"	"ÜberCharge ten of your Steam Community Friends."
"TF_MEDIC_INVITE_JOIN_CHARGE_NAME"	"House Call"
"TF_MEDIC_INVITE_JOIN_CHARGE_DESC"	"Join a game that one of your friends is in and then deploy an ÜberCharge on him."
"TF_MEDIC_HEAL_ACHIEVER_NAME"	"Bedside Manner"
"TF_MEDIC_HEAL_ACHIEVER_DESC"	"Be healing a teammate as he achieves an achievement of his own."
"TF_MEDIC_ACHIEVE_PROGRESS1_NAME"	"Medic Milestone 1"
"TF_MEDIC_ACHIEVE_PROGRESS1_DESC"	"Achieve 10 of the achievements in the Medic pack."
"TF_MEDIC_ACHIEVE_PROGRESS2_NAME"	"Medic Milestone 2"
"TF_MEDIC_ACHIEVE_PROGRESS2_DESC"	"Achieve 16 of the achievements in the Medic pack."
"TF_MEDIC_ACHIEVE_PROGRESS3_NAME"	"Medic Milestone 3"
"TF_MEDIC_ACHIEVE_PROGRESS3_DESC"	"Achieve 22 of the achievements in the Medic pack."
]],

pyro=[[
"TF_PYRO_KILL_MULTIWEAPONS_NAME"	"Combined Fire"
"TF_PYRO_KILL_MULTIWEAPONS_DESC"	"Use your shotgun to finish off 20 players you've ignited."
"TF_PYRO_SIMULBURN_SCOUTS_NAME"		"Weenie Roast"
"TF_PYRO_SIMULBURN_SCOUTS_DESC"		"Have 2 enemy Scouts on fire at the same time."
"TF_PYRO_FORCE_WATERJUMP_NAME"		"Baptism by Fire"
"TF_PYRO_FORCE_WATERJUMP_DESC"		"Force 10 burning enemies to jump into water."
"TF_PYRO_KILL_POSTDEATH_NAME"		"Fire and Forget"
"TF_PYRO_KILL_POSTDEATH_DESC"		"Kill 15 players while you're dead."
"TF_PYRO_KILL_SPIES_NAME"		"Firewall"
"TF_PYRO_KILL_SPIES_DESC"		"Ignite 5 Spies who have a sapper on a friendly building."
"TF_PYRO_KILL_CARRIERS_NAME"		"Cooking the Books"
"TF_PYRO_KILL_CARRIERS_DESC"		"Ignite 5 enemies carrying your intelligence."
"TF_PYRO_REVEAL_SPIES_NAME"		"Spontaneous Combustion"
"TF_PYRO_REVEAL_SPIES_DESC"		"Ignite 10 cloaked Spies."
"TF_PYRO_CAMP_TELEPORTERS_NAME"		"Trailblazer"
"TF_PYRO_CAMP_TELEPORTERS_DESC"		"Ignite 10 enemies that have recently used a teleporter."
"TF_PYRO_CAMP_POSITION_NAME"		"Camp Fire"
"TF_PYRO_CAMP_POSITION_DESC"		"Kill 3 enemies in a row, all within the same area."
"TF_PYRO_KILL_AXE_SMALL_NAME"		"Lumberjack"
"TF_PYRO_KILL_AXE_SMALL_DESC"		"Kill 3 people with your axe in one life."
"TF_PYRO_KILL_AXE_LARGE_NAME"		"Clearcutter"
"TF_PYRO_KILL_AXE_LARGE_DESC"		"Kill 6 people with your axe in one life."
"TF_PYRO_KILL_FROM_BEHIND_NAME"		"Hot on Your Heels"
"TF_PYRO_KILL_FROM_BEHIND_DESC"		"Kill 50 enemies with your flamethrower, from behind."
"TF_PYRO_BURN_SPIES_AS_YOU_NAME"	"I Fry"
"TF_PYRO_BURN_SPIES_AS_YOU_DESC"	"Ignite 10 disguised Spies."
"TF_PYRO_BURN_SNIPERS_ZOOMED_NAME"	"Firewatch"
"TF_PYRO_BURN_SNIPERS_ZOOMED_DESC"	"Ignite 10 Snipers while they are zoomed in."
"TF_PYRO_BURN_MEDICS_CHARGED_NAME"	"Burn Ward"
"TF_PYRO_BURN_MEDICS_CHARGED_DESC"	"Ignite 3 Medics that are ready to deploy an ÜberCharge."
"TF_PYRO_REFLECT_PROJECTILES_NAME"	"Hot Potato"
"TF_PYRO_REFLECT_PROJECTILES_DESC"	"Reflect 100 projectiles with your compressed air blast."
"TF_PYRO_KILL_HEAVIES_NAME"		"Makin' Bacon"
"TF_PYRO_KILL_HEAVIES_DESC"		"Kill 50 Heavies with your flamethrower."
"TF_PYRO_KILL_UNDERWATER_NAME"		"Plan B"
"TF_PYRO_KILL_UNDERWATER_DESC"		"Kill 10 enemies while you're both underwater."
"TF_PYRO_KILL_UBERCHARGE_NAME"		"Pyrotechnics"
"TF_PYRO_KILL_UBERCHARGE_DESC"		"Kill 3 enemies in a single ÜberCharge."
"TF_PYRO_DESTROY_BUILDINGS_NAME"	"Arsonist"
"TF_PYRO_DESTROY_BUILDINGS_DESC"	"Destroy 50 Engineer buildings."
"TF_PYRO_DEFEND_POINTS_NAME"		"Controlled Burn"
"TF_PYRO_DEFEND_POINTS_DESC"		"Ignite 50 enemies capturing one of your control points."
"TF_PYRO_KILL_GRIND_NAME"		"Firefighter"
"TF_PYRO_KILL_GRIND_DESC"		"Kill 500 enemies."
"TF_PYRO_DAMAGE_GRIND_NAME"		"Pyromancer"
"TF_PYRO_DAMAGE_GRIND_DESC"		"Do 1 million points of total fire damage."
"TF_PYRO_BURN_MEDICPAIR_NAME"		"Next of Kindling"
"TF_PYRO_BURN_MEDICPAIR_DESC"		"Ignite an enemy, and the Medic healing him."
"TF_PYRO_KILL_TAUNT_NAME"		"OMGWTFBBQ"
"TF_PYRO_KILL_TAUNT_DESC"		"Kill an enemy with a taunt."
"TF_PYRO_KILL_TEAMWORK_NAME"		"Second Degree Burn"
"TF_PYRO_KILL_TEAMWORK_DESC"		"Kill a burning enemy who was ignited by another Pyro."
"TF_PYRO_BURN_SPY_TAUNT_NAME"		"Got A Light?"
"TF_PYRO_BURN_SPY_TAUNT_DESC"		"Ignite an enemy Spy while he's flicking a cigarette."
"TF_PYRO_DOMINATE_LEAVESVR_NAME"	"BarbeQueQ"
"TF_PYRO_DOMINATE_LEAVESVR_DESC"	"Cause a dominated player to leave the server."
"TF_PYRO_REFLECT_CROCKET_KILL_NAME"	"Hotshot"
"TF_PYRO_REFLECT_CROCKET_KILL_DESC"	"Kill a Soldier with a reflected critical rocket."
"TF_PYRO_KILL_TAUNTERS_NAME"		"Dance Dance Immolation"
"TF_PYRO_KILL_TAUNTERS_DESC"		"Kill 3 enemies while they're taunting."
"TF_PYRO_DOUBLE_KO_NAME"		"Dead Heat"
"TF_PYRO_DOUBLE_KO_DESC"		"Kill an enemy in the same second that he kills you."
"TF_PYRO_BURN_RJ_SOLDIER_NAME"		"Pilot Light"
"TF_PYRO_BURN_RJ_SOLDIER_DESC"		"Ignite a rocket-jumping Soldier while he's in midair."
"TF_PYRO_FREEZECAM_TAUNTS_NAME"		"Freezer Burn"
"TF_PYRO_FREEZECAM_TAUNTS_DESC"		"Provide enemies with freezecam shots of each of your taunts."
"TF_PYRO_KILL_GRIND_LARGE_NAME"		"Fire Chief"
"TF_PYRO_KILL_GRIND_LARGE_DESC"		"Kill 1000 enemies."
"TF_PYRO_IGNITE_FLAREGUN_NAME"		"Attention Getter"
"TF_PYRO_IGNITE_FLAREGUN_DESC"		"Ignite 100 enemies with the flare gun."
"TF_PYRO_ACHIEVE_PROGRESS1_NAME"	"Pyro Milestone 1"
"TF_PYRO_ACHIEVE_PROGRESS1_DESC"	"Achieve 10 of the achievements in the Pyro pack."
"TF_PYRO_ACHIEVE_PROGRESS2_NAME"	"Pyro Milestone 2"
"TF_PYRO_ACHIEVE_PROGRESS2_DESC"	"Achieve 16 of the achievements in the Pyro pack."
"TF_PYRO_ACHIEVE_PROGRESS3_NAME"	"Pyro Milestone 3"
"TF_PYRO_ACHIEVE_PROGRESS3_DESC"	"Achieve 22 of the achievements in the Pyro pack."
]],

heavy=[[
"TF_HEAVY_DAMAGE_TAKEN_NAME"		"Iron Kurtain"
"TF_HEAVY_DAMAGE_TAKEN_DESC"		"Take 1000 points of damage in a single life."
"TF_HEAVY_DEFEND_MEDIC_NAME"		"Party Loyalty"
"TF_HEAVY_DEFEND_MEDIC_DESC"		"Kill 50 enemies within 3 seconds of them attacking your Medic."
"TF_HEAVY_ASSIST_MEDIC_LARGE_NAME"	"Division of Labor"
"TF_HEAVY_ASSIST_MEDIC_LARGE_DESC"	"Kill 10 enemies with a Medic assisting you, where neither of you die."
"TF_HEAVY_EARN_MEDIC_DOMINATION_NAME"	"Red Oktoberfest"
"TF_HEAVY_EARN_MEDIC_DOMINATION_DESC"	"Earn a domination for a Medic who's healing you."
"TF_HEAVY_KILL_TAUNT_NAME"			"Show Trial"
"TF_HEAVY_KILL_TAUNT_DESC"			"Kill an enemy with a taunt."
"TF_HEAVY_KILL_FLAG_CARRIERS_NAME"	"Crime and Punishment"
"TF_HEAVY_KILL_FLAG_CARRIERS_DESC"	"Kill 10 enemies carrying your intelligence."
"TF_HEAVY_KILL_MEDIC_PAIR_NAME"		"Class Struggle"
"TF_HEAVY_KILL_MEDIC_PAIR_DESC"		"Work with a friendly Medic to kill an enemy Heavy & Medic pair."
"TF_HEAVY_BLOCK_INVULN_HEAVY_NAME"	"Soviet Block"
"TF_HEAVY_BLOCK_INVULN_HEAVY_DESC"	"While invulnerable and on defense, block an invulnerable enemy Heavy's movement."
"TF_HEAVY_BLOCK_CART_NAME"			"Stalin the Kart"
"TF_HEAVY_BLOCK_CART_DESC"			"Block the enemy from moving the payload cart 25 times."
"TF_HEAVY_RECEIVE_UBER_GRIND_NAME"	"Supreme Soviet"
"TF_HEAVY_RECEIVE_UBER_GRIND_DESC"	"Get ÜberCharged 50 times."
"TF_HEAVY_STAND_NEAR_DISPENSER_NAME"	"Factory Worker"
"TF_HEAVY_STAND_NEAR_DISPENSER_DESC"	"Kill 20 enemies while being recharged by a dispenser."
"TF_HEAVY_ASSIST_HEAVY_GRIND_NAME"	"Soviet Union"
"TF_HEAVY_ASSIST_HEAVY_GRIND_DESC"	"Get 25 enemy kills where you either assist or are assisted by another Heavy."
"TF_HEAVY_CLEAR_STICKYBOMBS_NAME"	"0wn the Means of Production"
"TF_HEAVY_CLEAR_STICKYBOMBS_DESC"	"Remove 20 stickybombs by killing the Demomen who produced them."
"TF_HEAVY_KILL_UNDERWATER_NAME"		"Krazy Ivan"
"TF_HEAVY_KILL_UNDERWATER_DESC"		"Kill 100 enemies while both you and your victim are underwater."
"TF_HEAVY_TAKE_MULTI_DAMAGE_NAME"	"Rasputin"
"TF_HEAVY_TAKE_MULTI_DAMAGE_DESC"	"In a single life, get shot, burned, bludgeoned, and receive explosive damage."
"TF_HEAVY_KILL_DOMINATED_NAME"		"Icing on the Cake"
"TF_HEAVY_KILL_DOMINATED_DESC"		"Get 20 kills on players that you're dominating."
"TF_HEAVY_SURVIVE_CROCKET_NAME"		"Crock Block"
"TF_HEAVY_SURVIVE_CROCKET_DESC"		"Survive a direct hit from a critical rocket."
"TF_HEAVY_ASSIST_GRIND_NAME"		"Kollectivization"
"TF_HEAVY_ASSIST_GRIND_DESC"		"Get 1000 assists."
"TF_HEAVY_UNCOVER_SPIES_NAME"		"Spyalectical Materialism"
"TF_HEAVY_UNCOVER_SPIES_DESC"		"Kill or assist in killing 10 cloaked Spies."
"TF_HEAVY_KILL_WHILE_SPUNUP_NAME"	"Permanent Revolution"
"TF_HEAVY_KILL_WHILE_SPUNUP_DESC"	"Kill 5 enemies without spinning down your gun."
"TF_HEAVY_FIRE_LOTS_NAME"			"Heavy Industry"
"TF_HEAVY_FIRE_LOTS_DESC"			"Fire $200,000 worth of minigun rounds in a single life."
"TF_HEAVY_KILL_CRIT_PUNCH_NAME"		"Communist Mani-Fisto"
"TF_HEAVY_KILL_CRIT_PUNCH_DESC"		"Kill an enemy with a critical punch."
"TF_HEAVY_HEAL_MEDIKITS_NAME"		"Redistribution of Health"
"TF_HEAVY_HEAL_MEDIKITS_DESC"		"Heal 1000 damage with med-kits in a single life."
"TF_HEAVY_KILL_SHOTGUN_NAME"		"Rationing"
"TF_HEAVY_KILL_SHOTGUN_DESC"		"Kill an enemy with your shotgun while you're out of minigun ammo."
"TF_HEAVY_FIRST_TO_CAP_NAME"		"Vanguard Party"
"TF_HEAVY_FIRST_TO_CAP_DESC"		"Be the first on your team to start capturing a control point in a round."
"TF_HEAVY_PAYLOAD_CAP_GRIND_NAME"	"Pushkin the Kart"
"TF_HEAVY_PAYLOAD_CAP_GRIND_DESC"	"Get 50 caps on payload maps."
"TF_HEAVY_KILL_MIDAIR_MINIGUN_NAME"	"Marxman"
"TF_HEAVY_KILL_MIDAIR_MINIGUN_DESC"	"Kill 10 enemies in mid-air with the minigun."
"TF_HEAVY_DEFEND_CONTROL_POINT_NAME"	"Gorky Parked"
"TF_HEAVY_DEFEND_CONTROL_POINT_DESC"	"Kill 25 enemies while you're standing on a control point you own."
"TF_HEAVY_KILL_CAPPING_ENEMIES_NAME"	"Purge"
"TF_HEAVY_KILL_CAPPING_ENEMIES_DESC"	"Kill 15 enemies capturing a control point you own."
"TF_HEAVY_REVENGE_ASSIST_NAME"	"Lenin A Hand"
"TF_HEAVY_REVENGE_ASSIST_DESC"	"Help 5 teammates get revenge on their nemeses."
"TF_HEAVY_TELEPORT_FAST_KILL_NAME"	"Five Second Plan"
"TF_HEAVY_TELEPORT_FAST_KILL_DESC"	"Kill an enemy in the first 5 seconds after you exit a teleporter."
"TF_HEAVY_FREEZECAM_TAUNT_NAME"	"Photostroika"
"TF_HEAVY_FREEZECAM_TAUNT_DESC"	"Provide an enemy with a freezecam shot of you taunting while invulnerable."
"TF_HEAVY_EAT_SANDWICHES_NAME"		"Konspicuous Konsumption"
"TF_HEAVY_EAT_SANDWICHES_DESC"		"Eat 100 sandviches."
"TF_HEAVY_KILL_SCOUTS_NAME"	"Don't Touch Sandvich"
"TF_HEAVY_KILL_SCOUTS_DESC"	"Kill 50 Scouts using Natascha."
"TF_HEAVY_KILL_HEAVIES_GLOVES_NAME"	"Borscht Belt"
"TF_HEAVY_KILL_HEAVIES_GLOVES_DESC"	"Kill 10 Heavies with The K.G.B."
"TF_HEAVY_ACHIEVE_PROGRESS1_NAME"	"Heavy Milestone 1"
"TF_HEAVY_ACHIEVE_PROGRESS1_DESC"	"Achieve 10 of the achievements in the Heavy pack."
"TF_HEAVY_ACHIEVE_PROGRESS2_NAME"	"Heavy Milestone 2"
"TF_HEAVY_ACHIEVE_PROGRESS2_DESC"	"Achieve 16 of the achievements in the Heavy pack."
"TF_HEAVY_ACHIEVE_PROGRESS3_NAME"	"Heavy Milestone 3"
"TF_HEAVY_ACHIEVE_PROGRESS3_DESC"	"Achieve 22 of the achievements in the Heavy pack."
]],

scout=[[
"TF_SCOUT_FIRST_BLOOD_NAME"		"First Blood"
"TF_SCOUT_FIRST_BLOOD_DESC"		"Get the first kill in an Arena match."
"TF_SCOUT_FIRST_BLOOD_KILL_NAME"	"First Blood, Part 2"
"TF_SCOUT_FIRST_BLOOD_KILL_DESC"	"Kill 5 enemies with the First Blood crit buff."
"TF_SCOUT_WELL_EARLY_KILL_NAME"		"Quick Hook"
"TF_SCOUT_WELL_EARLY_KILL_DESC"		"Kill a player in Well before the round starts."
"TF_SCOUT_LIFETIME_KILLS_NAME"		"A Year to Remember"
"TF_SCOUT_LIFETIME_KILLS_DESC"		"Get 2004 lifetime kills."
"TF_SCOUT_IRON_MAN_KILLS_NAME"		"The Cycle"
"TF_SCOUT_IRON_MAN_KILLS_DESC"		"In a single life, kill an enemy while you are on the ground, in the air, and in the water."
"TF_SCOUT_DESTROY_TELEPORTERS_NAME"	"Closer"
"TF_SCOUT_DESTROY_TELEPORTERS_DESC"	"Destroy 3 teleporter entrances."
"TF_SCOUT_DESTROY_BUILDINGS_BEING_BUILT_NAME"	"If You Build It"
"TF_SCOUT_DESTROY_BUILDINGS_BEING_BUILT_DESC"	"Destroy 3 enemy buildings while they are still under construction."
"TF_SCOUT_DESTROY_SENTRY_WITH_PISTOL_NAME"	"Gun Down"
"TF_SCOUT_DESTROY_SENTRY_WITH_PISTOL_DESC"	"Destroy an active sentry gun using your pistol."
"TF_SCOUT_DOUBLE_JUMPS_NAME"		"Batter Up"
"TF_SCOUT_DOUBLE_JUMPS_DESC"		"Perform 1000 double jumps."
"TF_SCOUT_ASSIST_MEDIC_NAME"		"Doctoring the Ball"
"TF_SCOUT_ASSIST_MEDIC_DESC"		"Kill 3 enemies while under the effects of a Medic's ÜberCharge."
"TF_SCOUT_STEAL_SANDWICH_NAME"		"Dodgers 1, Giants 0"
"TF_SCOUT_STEAL_SANDWICH_DESC"		"Kill an enemy Heavy and take his Sandvich."
"TF_SCOUT_ACHIEVE_PROGRESS1_NAME"	"Scout Milestone 1"
"TF_SCOUT_ACHIEVE_PROGRESS1_DESC"	"Achieve 10 of the achievements in the Scout pack."
"TF_SCOUT_ACHIEVE_PROGRESS2_NAME"	"Scout Milestone 2"
"TF_SCOUT_ACHIEVE_PROGRESS2_DESC"	"Achieve 16 of the achievements in the Scout pack."
"TF_SCOUT_ACHIEVE_PROGRESS3_NAME"	"Scout Milestone 3"
"TF_SCOUT_ACHIEVE_PROGRESS3_DESC"	"Achieve 22 of the achievements in the Scout pack."
"TF_SCOUT_KILL_CHARGED_MEDICS_NAME"	"Batting the Doctor"
"TF_SCOUT_KILL_CHARGED_MEDICS_DESC"	"Kill a Medic that is ready to deploy an ÜberCharge."
"TF_SCOUT_SURVIVE_DAMAGE_NAME"		"I'm Bat Man"
"TF_SCOUT_SURVIVE_DAMAGE_DESC"		"Survive 500 damage in one life."
"TF_SCOUT_DOUBLEJUMP_KILL_NAME"		"Pop Fly"
"TF_SCOUT_DOUBLEJUMP_KILL_DESC"		"Kill 20 players while double-jumping."
"TF_SCOUT_FLAG_CAP_GRIND_NAME"		"Round-Tripper"
"TF_SCOUT_FLAG_CAP_GRIND_DESC"		"Capture the enemy intelligence 25 times."
"TF_SCOUT_THREE_FLAGCAPS_NAME"		"Triple Steal"
"TF_SCOUT_THREE_FLAGCAPS_DESC"		"Capture the enemy intelligence 3 times in a single CTF round."
"TF_SCOUT_DODGE_DAMAGE_NAME"		"Artful Dodger"
"TF_SCOUT_DODGE_DAMAGE_DESC"		"Dodge 1000 damage in a single life using your Bonk! Atomic Punch."
"TF_SCOUT_KNOCK_INTO_TRAIN_NAME"	"Fall Classic"
"TF_SCOUT_KNOCK_INTO_TRAIN_DESC"	"Cause an environmental death or suicide using the Force-A-Nature's knockback."
"TF_SCOUT_KILL_STUNNED_NAME"		"Strike Zone"
"TF_SCOUT_KILL_STUNNED_DESC"		"Kill 50 enemies while they are stunned."
"TF_SCOUT_STUN_INTO_TRAIN_NAME"		"Foul Territory"
"TF_SCOUT_STUN_INTO_TRAIN_DESC"		"Cause an environmental death by stunning an enemy."
"TF_SCOUT_STUN_UBER_ENEMIES_NAME"	"The Big Hurt"
"TF_SCOUT_STUN_UBER_ENEMIES_DESC"	"Stun 2 Medics that are ready to deploy an ÜberCharge."
"TF_SCOUT_STUN_CAPPING_ENEMIES_NAME"	"Brushback"
"TF_SCOUT_STUN_CAPPING_ENEMIES_DESC"	"Stun 50 enemies while they are capturing a point or pushing the cart."
"TF_SCOUT_MAX_STUNS_NAME"		"Moon Shot"
"TF_SCOUT_MAX_STUNS_DESC"		"Stun an enemy for the maximum possible duration by hitting them with a long-range ball."
"TF_SCOUT_STUN_SCOUT_WITH_THEIR_BALL_NAME"	"Beanball"
"TF_SCOUT_STUN_SCOUT_WITH_THEIR_BALL_DESC"	"Stun a Scout with their own ball."
"TF_SCOUT_KILL_IN_DODGE_COOLDOWN_NAME"	"Retire the Runner"
"TF_SCOUT_KILL_IN_DODGE_COOLDOWN_DESC"	"Kill a Scout while they are under the effect of Crit-a-Cola."
"TF_SCOUT_KILL_FROM_BEHIND_NAME"	"Caught Napping"
"TF_SCOUT_KILL_FROM_BEHIND_DESC"	"Kill 50 enemies from behind with the Force-A-Nature."
"TF_SCOUT_CAPTURE_LAST_POINT_NAME"	"Side Retired"
"TF_SCOUT_CAPTURE_LAST_POINT_DESC"	"Capture the last point in a CP map."
"TF_SCOUT_CAPTURE_THREE_POINTS_NAME"	"Triple Play"
"TF_SCOUT_CAPTURE_THREE_POINTS_DESC"	"Capture three capture points in a row in one life."
"TF_SCOUT_FAST_CAP_NAME"		"Stealing Home"
"TF_SCOUT_FAST_CAP_DESC"		"Start capping a capture point within a second of it becoming available."
"TF_SCOUT_START_AND_FINISH_CAP_NAME"	"Set the Table"
"TF_SCOUT_START_AND_FINISH_CAP_DESC"	"Initiate 10 point captures that ultimately succeed."
"TF_SCOUT_BLOCK_CAPS_NAME"		"Block the Plate"
"TF_SCOUT_BLOCK_CAPS_DESC"		"Block 50 point captures."
"TF_SCOUT_CARRIER_KILL_CARRIER_NAME"	"Belittled Beleaguer"
"TF_SCOUT_CARRIER_KILL_CARRIER_DESC"	"Kill an opposing player that has your intelligence while holding theirs."
"TF_SCOUT_CAP_FLAG_WITHOUT_ATTACKING_NAME" "No-Hitter"
"TF_SCOUT_CAP_FLAG_WITHOUT_ATTACKING_DESC" "Steal and then capture the enemy intelligence without firing a shot."
"TF_SCOUT_LONG_DISTANCE_RUNNER_NAME"	"Race for the Pennant"
"TF_SCOUT_LONG_DISTANCE_RUNNER_DESC"	"Run 25 kilometers."
"TF_SCOUT_TAUNT_KILL_NAME"		"Out of the Park"
"TF_SCOUT_TAUNT_KILL_DESC"		"Bat an enemy 25 meters."
]],

sniper=[[
"TF_SNIPER_JARATE_DOMINATED_NAME"	"Rode Hard, Put Away Wet"
"TF_SNIPER_JARATE_DOMINATED_DESC"	"Jarate an enemy that you're dominating."
"TF_SNIPER_FREEZECAM_HAT_NAME"		"Be Polite"
"TF_SNIPER_FREEZECAM_HAT_DESC"		"Provide an enemy with a freezecam shot of you doffing your hat."
"TF_SNIPER_RIFLE_NO_MISSING_NAME"	"Be Efficient"
"TF_SNIPER_RIFLE_NO_MISSING_DESC"	"Get 3 kills with the Sniper Rifle without missing a shot."
"TF_SNIPER_CAPTURE_FLAG_NAME"		"Have a Plan"
"TF_SNIPER_CAPTURE_FLAG_DESC"		"Capture the flag in CTF."
"TF_SNIPER_KILL_GRIND_NAME"		"Kill Everyone You Meet"
"TF_SNIPER_KILL_GRIND_DESC"		"Kill 1000 enemies."
"TF_SNIPER_KILL_WEAPONS_NAME"		"Triple Prey"
"TF_SNIPER_KILL_WEAPONS_DESC"		"In a single round, get a kill with 3 different weapons."
"TF_SNIPER_HEADSHOT_SNIPERS_NAME"	"Self-destruct Sequence"
"TF_SNIPER_HEADSHOT_SNIPERS_DESC"	"Headshot 10 enemy Snipers."
"TF_SNIPER_DESTROY_SENTRYGUNS_NAME"	"De-sentry-lized"
"TF_SNIPER_DESTROY_SENTRYGUNS_DESC"	"Destroy 3 Engineer sentry guns."
"TF_SNIPER_KILL_INVIS_SPY_NAME"		"Shoot the Breeze"
"TF_SNIPER_KILL_INVIS_SPY_DESC"		"Kill a fully invisible Spy in a single hit."
"TF_SNIPER_KILL_MIDAIR_SCOUT_NAME"	"Dropped Dead"
"TF_SNIPER_KILL_MIDAIR_SCOUT_DESC"	"Kill a Scout in midair with your Sniper Rifle or the Huntsman."
"TF_SNIPER_FREEZECAM_WAVE_NAME"		"The Last Wave"
"TF_SNIPER_FREEZECAM_WAVE_DESC"		"Provide an enemy with a freezecam shot of you waving to them."
"TF_SNIPER_DOMINATE_SNIPER_NAME"	"Australian Rules"
"TF_SNIPER_DOMINATE_SNIPER_DESC"	"Dominate an enemy Sniper."
"TF_SNIPER_KILL_SPIES_MELEE_NAME"	"Kook the Spook"
"TF_SNIPER_KILL_SPIES_MELEE_DESC"	"Kill 10 Spies with your Kukri."
"TF_SNIPER_HEADSHOT_DEMOMAN_NAME"	"Socket to Him"
"TF_SNIPER_HEADSHOT_DEMOMAN_DESC"	"Headshot an enemy Demoman."
"TF_SNIPER_KILL_RJER_NAME"		"Jumper Stumper"
"TF_SNIPER_KILL_RJER_DESC"		"Kill a rocket or grenade-jumping enemy in midair with your Sniper Rifle or the Huntsman."
"TF_SNIPER_KILL_OBJECTIVES_NAME"	"Not a Crazed Gunman, Dad"
"TF_SNIPER_KILL_OBJECTIVES_DESC"	"In a single life, kill 3 enemies while they are achieving an objective."
"TF_SNIPER_KILL_UNSCOPED_NAME"		"Trust Your Feelings"
"TF_SNIPER_KILL_UNSCOPED_DESC"		"Get 5 kills with the Sniper Rifle without your scope."
"TF_SNIPER_KILL_CHARGED_MEDIC_NAME"	"Überectomy"
"TF_SNIPER_KILL_CHARGED_MEDIC_DESC"	"Kill a Medic that is ready to deploy an ÜberCharge."
"TF_SNIPER_GET_BACKSTABBED_NAME"	"Consolation Prize"
"TF_SNIPER_GET_BACKSTABBED_DESC"	"Get backstabbed 50 times."
"TF_SNIPER_KILL_AT_ROUNDSTART_NAME"	"Enemy at the Gate"
"TF_SNIPER_KILL_AT_ROUNDSTART_DESC"	"Kill an opponent within the first second of a round."
"TF_SNIPER_HEADSHOT_POST_INVULN_NAME"	"Parting Shot"
"TF_SNIPER_HEADSHOT_POST_INVULN_DESC"	"Headshot an enemy player the moment his invulnerability wears off."
"TF_SNIPER_TOP_SCOREBOARD_GRIND_NAME"	"My Brilliant Career"
"TF_SNIPER_TOP_SCOREBOARD_GRIND_DESC"	"Top the scoreboard 10 times on teams of 6 or more players."
"TF_SNIPER_KILL_FAILED_SPY_NAME"	"Shock Treatment"
"TF_SNIPER_KILL_FAILED_SPY_DESC"	"Kill a spy whose backstab attempt was blocked by your Razorback."
"TF_SNIPER_JARATE_GROUP_NAME"		"Saturation Bombing"
"TF_SNIPER_JARATE_GROUP_DESC"		"Jarate 4 enemy players with a single throw."
"TF_SNIPER_JARATE_MEDIC_PAIR_NAME"	"Rain on Their Parade"
"TF_SNIPER_JARATE_MEDIC_PAIR_DESC"	"Jarate an enemy and the Medic healing him."
"TF_SNIPER_JARATE_REVEAL_SPY_NAME"	"Jarring Transition"
"TF_SNIPER_JARATE_REVEAL_SPY_DESC"	"Use Jarate to reveal a cloaked Spy."
"TF_SNIPER_JARATE_EXTINGUISH_NAME"	"Friendship is Golden"
"TF_SNIPER_JARATE_EXTINGUISH_DESC"	"Extinguish a burning teammate with your Jarate."
"TF_SNIPER_BOW_PIN_HEAVY_NAME"		"William Tell Overkill"
"TF_SNIPER_BOW_PIN_HEAVY_DESC"		"Pin an enemy Heavy to the wall via his head."
"TF_SNIPER_BOW_KILL_MEDIC_PAIR_NAME"	"Beaux and Arrows"
"TF_SNIPER_BOW_KILL_MEDIC_PAIR_DESC"	"Kill a Heavy & Medic pair with the bow."
"TF_SNIPER_BOW_KILL_FLAGCARRIER_NAME"	"Robbin’ Hood"
"TF_SNIPER_BOW_KILL_FLAGCARRIER_DESC"	"Take down an intelligence carrier with a single arrow."
"TF_SNIPER_BOW_PINCUSHION_NAME"		"Pincushion"
"TF_SNIPER_BOW_PINCUSHION_DESC"		"Hit an enemy with 3 arrows, without killing them."
"TF_SNIPER_JARATE_ASSISTS_NAME"		"Number One Assistant"
"TF_SNIPER_JARATE_ASSISTS_DESC"		"Score 5 assists with the Jarate in a single round."
"TF_SNIPER_JARATE_KILL_MELEE_NAME"	"Jarate Chop"
"TF_SNIPER_JARATE_KILL_MELEE_DESC"	"Jarate and then kill 3 enemies with your Kukri."
"TF_SNIPER_TAUNT_KILL_NAME"		"Shafted"
"TF_SNIPER_TAUNT_KILL_DESC"		"Stab an enemy with an arrow."
"TF_SNIPER_BOW_KILL_WHILEDEAD_NAME"	"Dead Reckoning"
"TF_SNIPER_BOW_KILL_WHILEDEAD_DESC"	"Kill an enemy with an arrow while you're dead."
"TF_SNIPER_ACHIEVE_PROGRESS1_NAME"		"Sniper Milestone 1"
"TF_SNIPER_ACHIEVE_PROGRESS1_DESC"		"Achieve 5 of the achievements in the Sniper pack."
"TF_SNIPER_ACHIEVE_PROGRESS2_NAME"		"Sniper Milestone 2"
"TF_SNIPER_ACHIEVE_PROGRESS2_DESC"		"Achieve 11 of the achievements in the Sniper pack."
"TF_SNIPER_ACHIEVE_PROGRESS3_NAME"		"Sniper Milestone 3"
"TF_SNIPER_ACHIEVE_PROGRESS3_DESC"		"Achieve 17 of the achievements in the Sniper pack."
]],

spy=[[
"TF_SPY_BACKSTAB_SNIPERS_NAME"			"Triplecrossed"
"TF_SPY_BACKSTAB_SNIPERS_DESC"			"Backstab 3 Snipers in a single life."
"TF_SPY_FREEZECAM_FLICK_NAME"			"For Your Eyes Only"
"TF_SPY_FREEZECAM_FLICK_DESC"			"Provide an enemy with a freezecam shot of you flicking a cigarette onto their corpse."
"TF_SPY_BACKSTAB_DISGUISED_SPY_NAME"		"Counter Espionage"
"TF_SPY_BACKSTAB_DISGUISED_SPY_DESC"		"Backstab a disguised Spy."
"TF_SPY_BACKSTAB_DISGUISE_TARGET_NAME"		"Identity Theft"
"TF_SPY_BACKSTAB_DISGUISE_TARGET_DESC"		"Backstab the enemy that you're currently disguised as."
"TF_SPY_TAUNT_KILL_NAME"			"The Man from P.U.N.C.T.U.R.E."
"TF_SPY_TAUNT_KILL_DESC"			"Stab an enemy while fencing."
"TF_SPY_BACKSTAB_MEDIC_HEALING_YOU_NAME"	"FYI I am a Spy"
"TF_SPY_BACKSTAB_MEDIC_HEALING_YOU_DESC"	"Backstab a Medic who has healed you in the last 5 seconds."
"TF_SPY_BACKSTAB_ENGY_SAP_BUILDING_NAME"	"The Man with the Broken Guns"
"TF_SPY_BACKSTAB_ENGY_SAP_BUILDING_DESC"	"Backstab an Engineer, then sap 3 of his buildings within 10 seconds."
"TF_SPY_SAP_BUILDING_BACKSTAB_ENGY_NAME"	"Sapsucker"
"TF_SPY_SAP_BUILDING_BACKSTAB_ENGY_DESC"	"Sap an enemy building, then backstab the Engineer who built it within 5 seconds."
"TF_SPY_BACKSTAB_MEDIC_PAIR_NAME"		"May I Cut In?"
"TF_SPY_BACKSTAB_MEDIC_PAIR_DESC"		"Backstab an enemy and the Medic healing him within 10 seconds of each other."
"TF_SPY_BACKSTAB_FRIENDS_NAME"			"Agent Provocateur"
"TF_SPY_BACKSTAB_FRIENDS_DESC"			"Backstab your Steam Community friends 10 times."
"TF_SPY_DOMINATE_SNIPER_NAME"			"The Melbourne Supremacy"
"TF_SPY_DOMINATE_SNIPER_DESC"			"Dominate a Sniper."
"TF_SPY_BUMP_CLOAKED_SPY_NAME"			"Spies Like Us"
"TF_SPY_BUMP_CLOAKED_SPY_DESC"			"While cloaked, bump into an enemy cloaked Spy."
"TF_SPY_KILL_SPY_WITH_KNIFE_NAME"		"A Cut Above"
"TF_SPY_KILL_SPY_WITH_KNIFE_DESC"		"Kill a gun-wielding Spy with your knife."
"TF_SPY_SURVIVE_BURNING_NAME"			"Burn Notice"
"TF_SPY_SURVIVE_BURNING_DESC"			"Survive 30 seconds after being ignited while cloaked."
"TF_SPY_BREAK_SHIELD_KILL_SNIPER_NAME"		"Die Another Way"
"TF_SPY_BREAK_SHIELD_KILL_SNIPER_DESC"		"Kill a Sniper after your backstab breaks his Razorback."
"TF_SPY_KILL_WORKING_ENGY_NAME"			"Constructus Interruptus"
"TF_SPY_KILL_WORKING_ENGY_DESC"			"Kill an Engineer who is working on a sentry gun."
"TF_SPY_FAST_CAP_NAME"				"On Her Majesty’s Secret Surface"
"TF_SPY_FAST_CAP_DESC"				"Start capping a capture point within a second of it becoming available."
"TF_SPY_MEDIC_HEALING_KILL_ENEMY_NAME"		"Insurance Fraud"
"TF_SPY_MEDIC_HEALING_KILL_ENEMY_DESC"		"Kill an enemy while you're being healed by an enemy Medic."
"TF_SPY_KILL_CP_DEFENDERS_NAME"			"Point Breaker"
"TF_SPY_KILL_CP_DEFENDERS_DESC"			"Kill 15 enemies who are standing on a control point they own."
"TF_SPY_BACKSTAB_DOMINATING_ENEMY_NAME"		"High Value Target"
"TF_SPY_BACKSTAB_DOMINATING_ENEMY_DESC"		"Backstab an enemy who is dominating 3 or more of your teammates."
"TF_SPY_REVENGE_WITH_BACKSTAB_NAME"		"Come in From the Cold"
"TF_SPY_REVENGE_WITH_BACKSTAB_DESC"		"Get a Revenge kill with a backstab."
"TF_SPY_KNIFE_KILL_WHILE_JARATED_NAME"		"Wetwork"
"TF_SPY_KNIFE_KILL_WHILE_JARATED_DESC"		"Stab an enemy to death while under the influence of Jarate."
"TF_SPY_BACKSTAB_QUICK_KILLS_NAME"		"You Only Shiv Thrice"
"TF_SPY_BACKSTAB_QUICK_KILLS_DESC"		"Backstab 3 enemies within 10 seconds."
"TF_SPY_BACKSTAB_GRIND_NAME"			"Spymaster"
"TF_SPY_BACKSTAB_GRIND_DESC"			"Backstab 1000 enemies."
"TF_SPY_SAPPER_GRIND_NAME"			"Sap Auteur"
"TF_SPY_SAPPER_GRIND_DESC"			"Destroy 1000 Engineer buildings with sappers."
"TF_SPY_SAPPER_TEAMWORK_NAME"			"Joint Operation"
"TF_SPY_SAPPER_TEAMWORK_DESC"			"Sap an enemy sentry gun within 3 seconds of a teammate sapping another."
"TF_SPY_BACKSTAB_MEDIC_CHARGED_NAME"		"Dr. Nooooo"
"TF_SPY_BACKSTAB_MEDIC_CHARGED_DESC"		"Backstab a Medic that is ready to deploy an ÜberCharge."
"TF_SPY_BACKSTAB_CAPPING_ENEMIES_NAME"		"Is It Safe?"
"TF_SPY_BACKSTAB_CAPPING_ENEMIES_DESC"		"Backstab 50 enemies who are capturing control points."
"TF_SPY_BACKSTAB_ENEMY_SWITCH_PYRO_NAME"	"Slash and Burn"
"TF_SPY_BACKSTAB_ENEMY_SWITCH_PYRO_DESC"	"Backstab an enemy, who then switches to Pyro before they respawn."
"TF_SPY_AMBASSADOR_GRIND_NAME"			"Diplomacy"
"TF_SPY_AMBASSADOR_GRIND_DESC"			"Kill 50 enemies with the Ambassador."
"TF_SPY_AMBASSADOR_SNIPER_GRIND_NAME"		"Skullpluggery"
"TF_SPY_AMBASSADOR_SNIPER_GRIND_DESC"		"Headshot 20 Snipers with the Ambassador."
"TF_SPY_FEIGN_DEATH_KILL_NAME"			"Sleeper Agent"
"TF_SPY_FEIGN_DEATH_KILL_DESC"			"Kill an enemy who triggered your feign death in the last 20 seconds."
"TF_SPY_AMBASSADOR_SCOUT_GRIND_NAME"		"Who's Your Daddy?"
"TF_SPY_AMBASSADOR_SCOUT_GRIND_DESC"		"Headshot 3 Scouts with the Ambassador."
"TF_SPY_CAMP_POSITION_NAME"			"Deep Undercover"
"TF_SPY_CAMP_POSITION_DESC"			"While using the Cloak and Dagger, kill the same enemy 3 times, all within the same area in a single life."
"TF_SPY_ACHIEVE_PROGRESS1_NAME"		"Spy Milestone 1"
"TF_SPY_ACHIEVE_PROGRESS1_DESC"		"Achieve 5 of the achievements in the Spy pack."
"TF_SPY_ACHIEVE_PROGRESS2_NAME"		"Spy Milestone 2"
"TF_SPY_ACHIEVE_PROGRESS2_DESC"		"Achieve 11 of the achievements in the Spy pack."
"TF_SPY_ACHIEVE_PROGRESS3_NAME"		"Spy Milestone 3"
"TF_SPY_ACHIEVE_PROGRESS3_DESC"		"Achieve 17 of the achievements in the Spy pack."
]],

--[[// Halloween Event
"TF_HALLOWEEN_COLLECT_PUMPKINS_NAME"		"Candy Coroner"
"TF_HALLOWEEN_COLLECT_PUMPKINS_DESC"		"Collect 20 Halloween pumpkins from dead players to unlock a hat."
"TF_HALLOWEEN_DOMINATE_FOR_HAT_NAME"		"Ghastly Gibus Grab"
"TF_HALLOWEEN_DOMINATE_FOR_HAT_DESC"		"Dominate a player wearing the Ghastly Gibus to earn your own."
"TF_HALLOWEEN_KILL_SCARED_PLAYER_NAME"		"Scared Stiff"
"TF_HALLOWEEN_KILL_SCARED_PLAYER_DESC"		"Kill a player scared by the ghost haunting KOTH Harvest."
"TF_HALLOWEEN_PUMPKIN_KILL_NAME"		"Attack o' Lantern"
"TF_HALLOWEEN_PUMPKIN_KILL_DESC"		"Cause the deaths of 5 players by exploding nearby pumpkin bombs."
"TF_HALLOWEEN_DISGUISED_SPY_KILL_NAME"		"Costume Contest"
"TF_HALLOWEEN_DISGUISED_SPY_KILL_DESC"		"Kill a Spy disguised as your current class."
]]

soldier=[[
"TF_SOLDIER_ACHIEVE_PROGRESS1_NAME"		"Soldier Milestone 1"
"TF_SOLDIER_ACHIEVE_PROGRESS1_DESC"		"Achieve 5 of the achievements in the Soldier pack."
"TF_SOLDIER_ACHIEVE_PROGRESS2_NAME"		"Soldier Milestone 2"
"TF_SOLDIER_ACHIEVE_PROGRESS2_DESC"		"Achieve 11 of the achievements in the Soldier pack."
"TF_SOLDIER_ACHIEVE_PROGRESS3_NAME"		"Soldier Milestone 3"
"TF_SOLDIER_ACHIEVE_PROGRESS3_DESC"		"Achieve 17 of the achievements in the Soldier pack."
"TF_SOLDIER_KILL_GROUP_WITH_CROCKET_NAME"	"Tri-Splatteral Damage"
"TF_SOLDIER_KILL_GROUP_WITH_CROCKET_DESC"	"Kill 3 enemies with a single critical rocket."
"TF_SOLDIER_KILL_TWO_DURING_ROCKET_JUMP_NAME"	"Death from Above"
"TF_SOLDIER_KILL_TWO_DURING_ROCKET_JUMP_DESC"	"Rocket jump and kill 2 enemies before you land."
"TF_SOLDIER_THREE_DOMINATIONS_NAME"		"Dominator"
"TF_SOLDIER_THREE_DOMINATIONS_DESC"		"Get 3 dominations in a single life."
"TF_SOLDIER_DEFEND_MEDIC_NAME"			"War Crime and Punishment"
"TF_SOLDIER_DEFEND_MEDIC_DESC"			"In a single life, kill 3 enemies who have damaged a Medic that is healing you."
"TF_SOLDIER_KILL_TAUNT_NAME"			"Spray of Defeat"
"TF_SOLDIER_KILL_TAUNT_DESC"			"Use a grenade to gib a player."
"TF_SOLDIER_DESTROY_SENTRY_OUT_OF_RANGE_NAME"	"Guns of the Navar0wned"
"TF_SOLDIER_DESTROY_SENTRY_OUT_OF_RANGE_DESC"	"Kill 5 Engineer sentries while you are standing outside of their range."
"TF_SOLDIER_KILL_SNIPER_WHILE_DEAD_NAME"	"Mutually Assured Destruction"
"TF_SOLDIER_KILL_SNIPER_WHILE_DEAD_DESC"	"Kill an enemy sniper with a rocket after he kills you."
"TF_SOLDIER_KILL_AIRBORNE_TARGET_WHILE_AIRBORNE_NAME"	"Wings of Glory"
"TF_SOLDIER_KILL_AIRBORNE_TARGET_WHILE_AIRBORNE_DESC"	"Kill an enemy soldier while both you and the target are airborne."
"TF_SOLDIER_KILL_ENGY_NAME"			"Engineer to Eternity"
"TF_SOLDIER_KILL_ENGY_DESC"			"Kill an Engineer as he repairs his sentry gun while it's under enemy fire."
"TF_SOLDIER_NEMESIS_SHOVEL_KILL_NAME"		"Trench Warfare"
"TF_SOLDIER_NEMESIS_SHOVEL_KILL_DESC"		"Kill your nemesis with a shovel."
"TF_SOLDIER_DESTROY_STICKIES_NAME"		"Bomb Squaddie"
"TF_SOLDIER_DESTROY_STICKIES_DESC"		"Destroy 10 sticky bombs with the shotgun in a single life."
"TF_SOLDIER_CROUCH_ROCKET_JUMP_NAME"		"Where Eagles Dare"
"TF_SOLDIER_CROUCH_ROCKET_JUMP_DESC"		"Get the highest possible rocket jump using jump and crouch."
"TF_SOLDIER_BUFF_FRIENDS_NAME"			"Banner of Brothers"
"TF_SOLDIER_BUFF_FRIENDS_DESC"			"Buff 5 steam friends at once with the Buff Banner."
"TF_SOLDIER_KILL_TWENTY_FROM_ABOVE_NAME"	"Screamin' Eagle"
"TF_SOLDIER_KILL_TWENTY_FROM_ABOVE_DESC"	"Kill 20 enemies from above."
"TF_SOLDIER_SHOOT_MULT_CRITS_NAME"		"Crockets Are Such B.S."
"TF_SOLDIER_SHOOT_MULT_CRITS_DESC"		"Shoot two non-boosted crit rockets in a row."
"TF_SOLDIER_KILL_DEFENSELESS_NAME"		"Geneva Contravention"
"TF_SOLDIER_KILL_DEFENSELESS_DESC"		"Kill 5 defenseless players after a single match has ended."
"TF_SOLDIER_KILL_ON_FIRE_NAME"			"Semper Fry"
"TF_SOLDIER_KILL_ON_FIRE_DESC"			"Kill 20 enemies while you are on fire."
"TF_SOLDIER_KILL_FIVE_STUNNED_NAME"		"The Longest Daze"
"TF_SOLDIER_KILL_FIVE_STUNNED_DESC"		"Kill 5 stunned players."
"TF_SOLDIER_FREEZECAM_GIBS_NAME"		"Gore-a! Gore-a! Gore-a!"
"TF_SOLDIER_FREEZECAM_GIBS_DESC"		"Provide the enemy with a freezecam of you taunting over 3 of their body parts."
"TF_SOLDIER_KILL_SPY_KILLER_NAME"		"War Crime Spybunal"
"TF_SOLDIER_KILL_SPY_KILLER_DESC"		"Kill a Spy who just backstabbed a teammate."
"TF_SOLDIER_DEFEND_CAP_THIRTY_TIMES_NAME"	"Hamburger Hill"
"TF_SOLDIER_DEFEND_CAP_THIRTY_TIMES_DESC"	"Defend a cap point 30 times."
"TF_SOLDIER_GIB_GRIND_NAME"			"Frags of our Fathers"
"TF_SOLDIER_GIB_GRIND_DESC"			"Gib 1000 people."
"TF_SOLDIER_RJ_EQUALIZER_KILL_NAME"		"Duty Bound"
"TF_SOLDIER_RJ_EQUALIZER_KILL_DESC"		"While rocket jumping kill an enemy with the Equalizer before you land."
"TF_SOLDIER_BUFF_TEAMMATES_NAME"		"The Boostie Boys"
"TF_SOLDIER_BUFF_TEAMMATES_DESC"		"Buff 15 teammates with the Buff Banner in a single life."
"TF_SOLDIER_KILL_DEMOMAN_GRIND_NAME"		"Out, Damned Scot!"
"TF_SOLDIER_KILL_DEMOMAN_GRIND_DESC"		"Kill 500 enemy Demomen"
"TF_SOLDIER_KILL_PYRO_NAME"			"Backdraft Dodger"
"TF_SOLDIER_KILL_PYRO_DESC"			"Kill a Pyro who has airblasted one of your rockets in the last 10 seconds."
"TF_SOLDIER_EQUALIZER_STREAK_NAME"		"Ain't Got Time to Bleed"
"TF_SOLDIER_EQUALIZER_STREAK_DESC"		"Kill 3 players with the Equalizer in a single life without being healed."
"TF_SOLDIER_KILL_WITH_EQUALIZER_WHILE_HURT_NAME""Near Death Experience"
"TF_SOLDIER_KILL_WITH_EQUALIZER_WHILE_HURT_DESC""Kill 20 enemies with your Equalizer while you have less than 25 health."
"TF_SOLDIER_BOUNCE_THEN_SHOTGUN_NAME"		"For Whom the Shell Trolls"
"TF_SOLDIER_BOUNCE_THEN_SHOTGUN_DESC"		"Bounce an opponent into the air with a rocket and then kill them with the shotgun before they land."
"TF_SOLDIER_KILL_AIRBORNE_WITH_DIRECT_HIT_NAME"	"Death From Below"
"TF_SOLDIER_KILL_AIRBORNE_WITH_DIRECT_HIT_DESC"	"Kill 10 opponents who are airborne with the Direct Hit."
"TF_SOLDIER_FREEZECAM_TAUNT_NAME"		"Worth a Thousand Words"
"TF_SOLDIER_FREEZECAM_TAUNT_DESC"		"Provide the enemy with a freezecam of your 21 gun salute."
"TF_SOLDIER_DUO_SOLDIER_KILLS_NAME"		"Brothers in Harms"
"TF_SOLDIER_DUO_SOLDIER_KILLS_DESC"		"Kill 10 enemies while assisting or being assisted by another Soldier."
"TF_SOLDIER_MVP_NAME"				"Medals of Honor"
"TF_SOLDIER_MVP_DESC"				"Finish a round as an MVP on a team of 6 or more players 10 times."
"TF_SOLDIER_RIDE_THE_CART_NAME"			"Ride of the Valkartie"
"TF_SOLDIER_RIDE_THE_CART_DESC"			"Ride the cart for 30 seconds."
"TF_SOLDIER_ASSIST_MEDIC_UBER_NAME"		"S*M*A*S*H"
"TF_SOLDIER_ASSIST_MEDIC_UBER_DESC"		"Assist a Medic in exploding 5 enemies with a single ÜberCharge."
]],

demoman=[[
"TF_DEMOMAN_KILL_SOLDIER_GRIND_NAME"		"Kilt in Action"
"TF_DEMOMAN_KILL_SOLDIER_GRIND_DESC"		"Kill 500 enemy Soldiers"
"TF_DEMOMAN_DESTROY_BUILDINGS_WITH_MEDIC_NAME"	"Tam O'Shatter"
"TF_DEMOMAN_DESTROY_BUILDINGS_WITH_MEDIC_DESC"	"Destroy 5 enemy Engineer buildings during a single ÜberCharge from a Medic."
"TF_DEMOMAN_DECAPITATE_CLOAKED_SPY_NAME"	"Shorn Connery"
"TF_DEMOMAN_DECAPITATE_CLOAKED_SPY_DESC"	"Decapitate a cloaked Spy."
"TF_DEMOMAN_KILL_X_WITH_DIRECTPIPE_NAME"	"Laddy Macdeth"
"TF_DEMOMAN_KILL_X_WITH_DIRECTPIPE_DESC"	"Kill 50 enemies with direct hits from the Grenade Launcher."
"TF_DEMOMAN_BOUNCE_AND_KILL_NAME"		"Caber Toss"
"TF_DEMOMAN_BOUNCE_AND_KILL_DESC"		"Bounce an enemy into the air and kill them before they land."
"TF_DEMOMAN_DECAPITATE_PLAYERS_NAME"		"Brainspotting"
"TF_DEMOMAN_DECAPITATE_PLAYERS_DESC"		"Decapitate 50 enemy players."
"TF_DEMOMAN_DECAPITATE_PLAYERS_FAST_NAME"	"Left 4 Heads"
"TF_DEMOMAN_DECAPITATE_PLAYERS_FAST_DESC"	"Decapitate 4 players with only 10 seconds between each kill."
"TF_DEMOMAN_DUO_DEMOMAN_KILLS_NAME"		"Well Plaid!"
"TF_DEMOMAN_DUO_DEMOMAN_KILLS_DESC"		"Kill 10 enemies while assisting or being assisted by another Demoman."
"TF_DEMOMAN_KILL_TWO_DURING_STICKYJUMP_NAME"	"Double Mauled Scotch"
"TF_DEMOMAN_KILL_TWO_DURING_STICKYJUMP_DESC"	"Kill 2 people in a single sticky jump."
"TF_DEMOMAN_KILL_PLAYER_AFTER_TP_NAME"		"Loch Ness Bombster"
"TF_DEMOMAN_KILL_PLAYER_AFTER_TP_DESC"		"Kill an enemy player with sticky bombs within 5 seconds of them teleporting."
"TF_DEMOMAN_DOMINATE_THREE_ENGINEERS_NAME"	"Three Times a Laddy"
"TF_DEMOMAN_DOMINATE_THREE_ENGINEERS_DESC"	"Dominate 3 Engineers."
"TF_DEMOMAN_KILL_BUILDING_DIRECT_HIT_NAME"	"Blind Fire"
"TF_DEMOMAN_KILL_BUILDING_DIRECT_HIT_DESC"	"Destroy an Engineer building that you can't see with a direct hit from your Grenade Launcher."
"TF_DEMOMAN_MELEE_KILL_WHILE_STICKYJUMPING_NAME""The Scottish Play"
"TF_DEMOMAN_MELEE_KILL_WHILE_STICKYJUMPING_DESC""Get a melee kill while sticky jumping."
"TF_DEMOMAN_KILL_ENGI_SENTRY_DISPENSER_NAME"	"The Argyle Sap"
"TF_DEMOMAN_KILL_ENGI_SENTRY_DISPENSER_DESC"	"Blow up an Engineer, his sentry gun, and his dispenser with a single Sticky bomb detonation."
"TF_DEMOMAN_DECAPITATE_EQUALIZER_NAME"		"Slammy Slayvis Woundya"
"TF_DEMOMAN_DECAPITATE_EQUALIZER_DESC"		"Decapitate an enemy Soldier who is brandishing the Equalizer."
"TF_DEMOMAN_DECAPITATE_NEMESIS_NAME"		"There Can Be Only One"
"TF_DEMOMAN_DECAPITATE_NEMESIS_DESC"		"Decapitate your nemesis."
"TF_DEMOMAN_DAMAGE_GRIND_NAME"			"Tartan Spartan"
"TF_DEMOMAN_DAMAGE_GRIND_DESC"			"Do 1 million points of total blast damage."
"TF_DEMOMAN_KILL_X_CAPPING_ONEDET_NAME"		"Scotch Guard"
"TF_DEMOMAN_KILL_X_CAPPING_ONEDET_DESC"		"Kill 3 enemies capping or pushing a cart in a single Stickybomb detonation 3 separate times."
"TF_DEMOMAN_KILL_X_DEFENDING_NAME"		"Bravehurt"
"TF_DEMOMAN_KILL_X_DEFENDING_DESC"		"Kill 25 players defending a capture point or cart."
"TF_DEMOMAN_DESTROY_BUILDINGS_GRIND_NAME"	"Cry Some Moor!"
"TF_DEMOMAN_DESTROY_BUILDINGS_GRIND_DESC"	"Destroy 50 buildings."
"TF_DEMOMAN_KILL_X_HEAVIES_FULLHP_ONEDET_NAME"	"The Stickening"
"TF_DEMOMAN_KILL_X_HEAVIES_FULLHP_ONEDET_DESC"	"Kill 5 Heavies from full health with a single sticky bomb detonation."
"TF_DEMOMAN_KILL_X_SCOUTS_PYROS_NAME"		"Glasg0wned"
"TF_DEMOMAN_KILL_X_SCOUTS_PYROS_DESC"		"Kill 25 Scouts and Pyros with the Grenade Launcher."
"TF_DEMOMAN_TAUNT_KILL_NAME"			"Scotch Tap"
"TF_DEMOMAN_TAUNT_KILL_DESC"			"Glory in the slaughter of your enemies using the Eyelander."
"TF_DEMOMAN_CHARGE_KILL_NAME"			"The Targe Charge"
"TF_DEMOMAN_CHARGE_KILL_DESC"			"Charge and kill someone with your shield bash."
"TF_DEMOMAN_CRIT_SWORD_KILL_NAME"		"Beat Me Up, Scotty"
"TF_DEMOMAN_CRIT_SWORD_KILL_DESC"		"Use a critical swing with the Eyelander to kill 5 enemy players."
"TF_DEMOMAN_AIR_BURST_KILLS_NAME"		"Something Stickied This Way Comes"
"TF_DEMOMAN_AIR_BURST_KILLS_DESC"		"Kill 30 players with air burst sticky bombs."
"TF_DEMOMAN_STICKYJUMP_CAP_NAME"		"The High Road"
"TF_DEMOMAN_STICKYJUMP_CAP_DESC"		"Sticky jump onto a cap point and capture it."
"TF_DEMOMAN_FREEZECAM_SMILE_NAME"		"Bloody Merry"
"TF_DEMOMAN_FREEZECAM_SMILE_DESC"		"Provide an enemy player with a freeze cam of your smiling face."
"TF_DEMOMAN_FREEZECAM_RUMP_NAME"		"Second Eye"
"TF_DEMOMAN_FREEZECAM_RUMP_DESC"		"Provide an enemy player with a freeze cam of you shaking your rump."
"TF_DEMOMAN_ENVIRONMENTAL_KILL_NAME"		"He Who Celt It"
"TF_DEMOMAN_ENVIRONMENTAL_KILL_DESC"		"Use the Sticky Launcher to kill an enemy player via environmental damage."
"TF_DEMOMAN_DESTROY_X_STICKYBOMBS_NAME"		"Robbed Royal"
"TF_DEMOMAN_DESTROY_X_STICKYBOMBS_DESC"		"Destroy 100 enemy sticky bombs with the Scottish Resistance."
"TF_DEMOMAN_STICKJUMP_DISTANCE_NAME"		"Highland Fling"
"TF_DEMOMAN_STICKJUMP_DISTANCE_DESC"		"Sticky jump a really long way..."
"TF_DEMOMAN_KILL3_WITH_DETONATION_NAME"		"Pipebagger"
"TF_DEMOMAN_KILL3_WITH_DETONATION_DESC"		"Kill at least three players with a single detonation of sticky bombs."
"TF_DEMOMAN_KILLXSAPPINGSPIES_NAME"		"Spynal Tap"
"TF_DEMOMAN_KILLXSAPPINGSPIES_DESC"		"Kill 20 spies within 5 seconds of them sapping a friendly building."
"TF_DEMOMAN_KILL3_WITH_PIPE_SETUPS_NAME"	"Sticky Thump"
"TF_DEMOMAN_KILL3_WITH_PIPE_SETUPS_DESC"	"Using the Scottish Resistance, kill 3 players in separate explosions without placing new sticky bombs."
"TF_DEMOMAN_ACHIEVE_PROGRESS1_NAME"		"Demoman Milestone 1"
"TF_DEMOMAN_ACHIEVE_PROGRESS1_DESC"		"Achieve 5 of the achievements in the Demoman pack."
"TF_DEMOMAN_ACHIEVE_PROGRESS2_NAME"		"Demoman Milestone 2"
"TF_DEMOMAN_ACHIEVE_PROGRESS2_DESC"		"Achieve 11 of the achievements in the Demoman pack."
"TF_DEMOMAN_ACHIEVE_PROGRESS3_NAME"		"Demoman Milestone 3"
"TF_DEMOMAN_ACHIEVE_PROGRESS3_DESC"		"Achieve 17 of the achievements in the Demoman pack."
]],

engineer=[[
"TF_ENGINEER_ACHIEVE_PROGRESS1_NAME"				"Engineer Milestone 1"
"TF_ENGINEER_ACHIEVE_PROGRESS1_DESC"				"Achieve 5 of the achievements in the Engineer pack."
"TF_ENGINEER_ACHIEVE_PROGRESS2_NAME"				"Engineer Milestone 2"
"TF_ENGINEER_ACHIEVE_PROGRESS2_DESC"				"Achieve 11 of the achievements in the Engineer pack."
"TF_ENGINEER_ACHIEVE_PROGRESS3_NAME"				"Engineer Milestone 3"
"TF_ENGINEER_ACHIEVE_PROGRESS3_DESC"				"Achieve 17 of the achievements in the Engineer pack."
"TF_ENGINEER_TELEPORT_GRIND_NAME"				"Battle Rustler"
"TF_ENGINEER_TELEPORT_GRIND_DESC"				"Teleport 100 team members into battle."
"TF_ENGINEER_DISPENSER_EXTINGUISH_NAME"				"The Extinguished Gentleman"
"TF_ENGINEER_DISPENSER_EXTINGUISH_DESC"				"Have dispensers you built extinguish 20 burning players."
"TF_ENGINEER_REVENGE_CRIT_SENTRY_KILLER_NAME"			"Revengineering"
"TF_ENGINEER_REVENGE_CRIT_SENTRY_KILLER_DESC"			"Use a revenge crit to kill the enemy player that destroyed your sentry gun."
"TF_ENGINEER_MANUAL_CLOAKED_SPY_KILL_NAME"			"Search Engine"
"TF_ENGINEER_MANUAL_CLOAKED_SPY_KILL_DESC"			"Kill 3 cloaked Spies with a sentry gun under control of your Wrangler."
"TF_ENGINEER_MANUAL_SENTRY_KILLS_BEYOND_RANGE_NAME"		"Pownd on the Range"
"TF_ENGINEER_MANUAL_SENTRY_KILLS_BEYOND_RANGE_DESC"		"Kill 10 enemies outside the normal sentry gun range using the Wrangler."
"TF_ENGINEER_MANUAL_SENTRY_ABSORB_DMG_NAME"			"Building Block"
"TF_ENGINEER_MANUAL_SENTRY_ABSORB_DMG_DESC"			"Have a sentry shielded by the Wrangler absorb 500 damage without being destroyed."
"TF_ENGINEER_REVENGE_CRIT_LIFE_NAME"				"Unforgiven"
"TF_ENGINEER_REVENGE_CRIT_LIFE_DESC"				"Kill 3 enemies with revenge crits without dying."
"TF_ENGINEER_KILL_SPY_TWO_SAPPERS_NAME"				"Quick Draw"
"TF_ENGINEER_KILL_SPY_TWO_SAPPERS_DESC"				"Kill a spy and two sappers within 10 seconds."
"TF_ENGINEER_KILL_DISGUISED_SPY_NAME"				"The Wrench Connection"
"TF_ENGINEER_KILL_DISGUISED_SPY_DESC"				"Kill a disguised spy with your Wrench."
"TF_ENGINEER_UPGRADE_BUILDINGS_NAME"				"Silent Pardner"
"TF_ENGINEER_UPGRADE_BUILDINGS_DESC"				"Upgrade 50 buildings built by other team members."
"TF_ENGINEER_DESTROY_SAPPERS_NAME"				"Fistful of Sappers"
"TF_ENGINEER_DESTROY_SAPPERS_DESC"				"Destroy 25 sappers on buildings built by other team members."
"TF_ENGINEER_REPAIR_SENTRY_W_MEDIC_NAME"			"Doc, Stock, and Barrel"
"TF_ENGINEER_REPAIR_SENTRY_W_MEDIC_DESC"			"Repair a sentry gun under fire while being healed by a Medic."
"TF_ENGINEER_SENTRY_KILL_LIFETIME_GRIND_NAME"			"Best Little Slaughterhouse in Texas"
"TF_ENGINEER_SENTRY_KILL_LIFETIME_GRIND_DESC"			"Rack up 5000 kills with your sentry guns."
"TF_ENGINEER_SENTRY_AVENGES_YOU_NAME"				"Frontier Justice"
"TF_ENGINEER_SENTRY_AVENGES_YOU_DESC"				"Have your sentry kill the enemy that just killed you within 10 seconds."
"TF_ENGINEER_FREEZECAM_TAUNT_NAME"				"Six-String Stringer"
"TF_ENGINEER_FREEZECAM_TAUNT_DESC"				"Provide an enemy player with a freeze cam of your guitar playing skills."
"TF_ENGINEER_FREEZECAM_SENTRY_NAME"				"Uncivil Engineer"
"TF_ENGINEER_FREEZECAM_SENTRY_DESC"				"Provide an enemy player with a freeze cam of you and the sentry that just killed them."
"TF_ENGINEER_SHOTGUN_KILL_PREV_SENTRY_TARGET_NAME"		"Texas Two-Step"
"TF_ENGINEER_SHOTGUN_KILL_PREV_SENTRY_TARGET_DESC"		"Use your shotgun to finish off an enemy recently damaged by your sentry gun."
"TF_ENGINEER_DISPENSER_HEAL_GROUP_NAME"				"Doc Holiday"
"TF_ENGINEER_DISPENSER_HEAL_GROUP_DESC"				"Have a dispenser heal 3 teammates at the same time."
"TF_ENGINEER_SENTRY_KILL_CAPS_NAME"				"No Man's Land"
"TF_ENGINEER_SENTRY_KILL_CAPS_DESC"				"Use a sentry gun to kill 25 enemy players that are capturing a point."
"TF_ENGINEER_KILL_FLAG_CARRIERS_NAME"				"Trade Secrets"
"TF_ENGINEER_KILL_FLAG_CARRIERS_DESC"				"Kill 20 players carrying the intelligence."
"TF_ENGINEER_WASTE_METAL_GRIND_NAME"				"Death Metal"
"TF_ENGINEER_WASTE_METAL_GRIND_DESC"				"Pick up 10,000 waste metal from pieces of destroyed buildings."
"TF_ENGINEER_HELP_BUILD_STRUCTURE_NAME"				"Land Grab"
"TF_ENGINEER_HELP_BUILD_STRUCTURE_DESC"				"Help a teammate construct a building."
"TF_ENGINEER_REMOVE_SAPPER_LONG_DIST_NAME"			"Get Along!"
"TF_ENGINEER_REMOVE_SAPPER_LONG_DIST_DESC"			"Manage to get to and then remove a sapper placed on your building while you were several meters away."
"TF_ENGINEER_DESTROY_STICKIES_NAME"				"How the Pests Was Gunned"
"TF_ENGINEER_DESTROY_STICKIES_DESC"				"Destroy 50 enemy stickybombs lying in range of friendly buildings."
"TF_ENGINEER_TAUNT_KILL_NAME"					"Honky Tonk Man"
"TF_ENGINEER_TAUNT_KILL_DESC"					"Smash an enemy player's head in with your guitar."
"TF_ENGINEER_KILL_SNIPERS_SENTRY_NAME"				"Breaking Morant"
"TF_ENGINEER_KILL_SNIPERS_SENTRY_DESC"				"Kill 10 Snipers with a sentry gun under control of your Wrangler."
"TF_ENGINEER_HELP_MANUAL_SENTRY_NAME"				"Rio Grind"
"TF_ENGINEER_HELP_MANUAL_SENTRY_DESC"				"Perform 50 repairs and/or reloads on a Sentry gun being Wrangled by another Engineer."
"TF_ENGINEER_KILL_SENTRY_WITH_SENTRY_NAME"			"Patent Protection"
"TF_ENGINEER_KILL_SENTRY_WITH_SENTRY_DESC"			"Destroy an enemy Engineer's sentry gun with a sentry under control of your Wrangler."
"TF_ENGINEER_MOVE_SENTRY_GET_KILL_NAME"				"If You Build It, They Will Die"
"TF_ENGINEER_MOVE_SENTRY_GET_KILL_DESC"				"Haul a level 3 sentry gun into a position where it achieves a kill shortly after being redeployed."
"TF_ENGINEER_BUILDING_CARRY_NAME"				"Texas Ranger"
"TF_ENGINEER_BUILDING_CARRY_DESC"				"Haul buildings 1 km over your career."
"TF_ENGINEER_KILL_ASSIST_NAME"					"Deputized"
"TF_ENGINEER_KILL_ASSIST_DESC"					"Get 10 assists with another Engineer where a sentry gun was involved in the kill."
"TF_ENGINEER_DISPENSER_HEAL_GRIND_NAME"				"Drugstore Cowboy"
"TF_ENGINEER_DISPENSER_HEAL_GRIND_DESC"				"Have dispensers you created dispense a combined amount of 100,000 health over your career."
"TF_ENGINEER_REPAIR_TEAM_GRIND_NAME"				"Circle the Wagons"
"TF_ENGINEER_REPAIR_TEAM_GRIND_DESC"				"Repair 50,000 damage to friendly buildings constructed by other players."
"TF_ENGINEER_TANK_DAMAGE_NAME"					"Built to Last"
"TF_ENGINEER_TANK_DAMAGE_DESC"					"Help a single building tank over 2000 damage without being destroyed."
"TF_ENGINEER_HEAVY_ASSIST_NAME"					"(Not So) Lonely Are the Brave"
"TF_ENGINEER_HEAVY_ASSIST_DESC"					"Keep a Heavy healed with your dispenser while he gains 5 kills."
]],
}

order={'medic','pyro','heavy','scout','sniper','spy','soldier','demoman','engineer'}

io.output"data/achievements.lua"

io.write[[
--encoding: utf-8
--(the Ü in Übercharge, fancy quote characters)

tf={
]]
for i=1,#order do
  io.write(string.format("  %s ={\n",order[i]))
  for id,name,desc in string.gmatch(achievements[ order[i] ],
  '"TF_'..string.upper(order[i])..'_(.-)_NAME"%s-"(.-)"\n'..
  '"TF_'..string.upper(order[i])..'_%1_DESC"%s-"(.-)"') do
    io.write(string.format(
      "    %s ={ name= %q,\n      desc= %q},\n",string.lower(id),name,desc))
  end
  io.write"  },\n"
end
io.write"}\n\nreturn tf\n"
